#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////
#//
#//%/////////////////////////////////////////////////////////////////////////


ROOT = ../../../..
DIRS = \
	$(ROOT)/src/Providers/UNIXProviders/FibreProtocolService \
\
	$(ROOT)/src/Providers/UNIXProviders/WakeUpService \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemSnapshotService \
\
	$(ROOT)/src/Providers/UNIXProviders/ResourcePoolConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/HelpService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageRelocationService \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSService \
\
	$(ROOT)/src/Providers/UNIXProviders/PolicyActivationService \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIPathConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/BIOSService \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPortConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiPortConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/VRFConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/ReplicationService \
\
	$(ROOT)/src/Providers/UNIXProviders/AccountManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/VerificationService \
\
	$(ROOT)/src/Providers/UNIXProviders/CertificateAuthority \
\
	$(ROOT)/src/Providers/UNIXProviders/Notary \
\
	$(ROOT)/src/Providers/UNIXProviders/KeyBasedCredentialManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/CertificateManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/KerberosKeyDistributionCenter \
\
	$(ROOT)/src/Providers/UNIXProviders/PublicKeyManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/SharedSecretService \
\
	$(ROOT)/src/Providers/UNIXProviders/IdentityManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageHardwareIDManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/AuthorizationService \
\
	$(ROOT)/src/Providers/UNIXProviders/PrivilegeManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/RoleBasedAuthorizationService \
\
	$(ROOT)/src/Providers/UNIXProviders/AccessControlService \
\
	$(ROOT)/src/Providers/UNIXProviders/WBEMServer \
\
	$(ROOT)/src/Providers/UNIXProviders/LaunchInContextService \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/MetricService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageNameBindingService \
\
	$(ROOT)/src/Providers/UNIXProviders/ZoneService \
\
	$(ROOT)/src/Providers/UNIXProviders/ControllerConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/GroupMaskingMappingService \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseService \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskPartitionConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/ConfigurationReportingService \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerTopologyService \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPolicyService \
\
	$(ROOT)/src/Providers/UNIXProviders/BasicExecutionService \
\
	$(ROOT)/src/Providers/UNIXProviders/SpareConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageElementCompositionService \
\
	$(ROOT)/src/Providers/UNIXProviders/OpaqueManagementDataService \
\
	$(ROOT)/src/Providers/UNIXProviders/FingerprintMatchingService \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolService \
\
	$(ROOT)/src/Providers/UNIXProviders/WBEMProtocolService \
\
	$(ROOT)/src/Providers/UNIXProviders/TierService \
\
	$(ROOT)/src/Providers/UNIXProviders/TierPolicyService \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicationService \
\
	$(ROOT)/src/Providers/UNIXProviders/FileImportService \
\
	$(ROOT)/src/Providers/UNIXProviders/VTLStatisticalDataService \
\
	$(ROOT)/src/Providers/UNIXProviders/DropThresholdCalculationService \
\
	$(ROOT)/src/Providers/UNIXProviders/TokenBucketMeterService \
\
	$(ROOT)/src/Providers/UNIXProviders/EWMAMeterService \
\
	$(ROOT)/src/Providers/UNIXProviders/AverageRateMeterService \
\
	$(ROOT)/src/Providers/UNIXProviders/ToSMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/Priority8021QMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/DSCPMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/PreambleMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/ClassifierService \
\
	$(ROOT)/src/Providers/UNIXProviders/ClassifierElement \
\
	$(ROOT)/src/Providers/UNIXProviders/PacketSchedulingService \
\
	$(ROOT)/src/Providers/UNIXProviders/NonWorkConservingSchedulingService \
\
	$(ROOT)/src/Providers/UNIXProviders/REDDropperService \
\
	$(ROOT)/src/Providers/UNIXProviders/HeadTailDropper \
\
	$(ROOT)/src/Providers/UNIXProviders/WeightedREDDropperService \
\
	$(ROOT)/src/Providers/UNIXProviders/QueuingService \
\
	$(ROOT)/src/Providers/UNIXProviders/BootService \
\
	$(ROOT)/src/Providers/UNIXProviders/AFService \
\
	$(ROOT)/src/Providers/UNIXProviders/EFService \
\
	$(ROOT)/src/Providers/UNIXProviders/FlowService \
\
	$(ROOT)/src/Providers/UNIXProviders/Hdr8021PService \
\
	$(ROOT)/src/Providers/UNIXProviders/PrecedenceService \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintService \
\
	$(ROOT)/src/Providers/UNIXProviders/TimeService \
\
	$(ROOT)/src/Providers/UNIXProviders/SoftwareInstallationService \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANService \
\
	$(ROOT)/src/Providers/UNIXProviders/Specific802dot1QVLANService \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerUtilizationManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/ClusteringService \
\
	$(ROOT)/src/Providers/UNIXProviders/SharedDeviceManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/BatchService \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/OOBAlertService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/IPConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemMigrationService \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSCrossConnect \
\
	$(ROOT)/src/Providers/UNIXProviders/PlatformWatchdogService \
\
	$(ROOT)/src/Providers/UNIXProviders/FCHBADiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/RAIDDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/CPUDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetNICDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/OpticalDriveDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/OpticalDriveDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDriveDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/IBSubnetManager \
\
	$(ROOT)/src/Providers/UNIXProviders/ObjectManager \
\
	$(ROOT)/src/Providers/UNIXProviders/ObjectManagerAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/ProviderObjectManagerAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemStatisticsService \
\
	$(ROOT)/src/Providers/UNIXProviders/BlockStatisticsService \
\
	$(ROOT)/src/Providers/UNIXProviders/USBRedirectionService \
\
	$(ROOT)/src/Providers/UNIXProviders/TextRedirectionService \
\
	$(ROOT)/src/Providers/UNIXProviders/BGPService \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFService \
\
	$(ROOT)/src/Providers/UNIXProviders/NATService \
\
	$(ROOT)/src/Providers/UNIXProviders/TransparentBridgingService \
\
	$(ROOT)/src/Providers/UNIXProviders/SourceRoutingService \
\
	$(ROOT)/src/Providers/UNIXProviders/SpanningTreeService \
\
	$(ROOT)/src/Providers/UNIXProviders/SwitchService \
\
	$(ROOT)/src/Providers/UNIXProviders/FileExportService \
\
	$(ROOT)/src/Providers/UNIXProviders/DHCPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/SSHProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/CLPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IPXProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IPsecSAEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IKESAEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LANEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/WirelessLANEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/UDPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/TCPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFVirtualInterface \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LinkAggregator8023ad \
\
	$(ROOT)/src/Providers/UNIXProviders/ATAProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IPEncapsulationInterface \
\
	$(ROOT)/src/Providers/UNIXProviders/IPSubinterface \
\
	$(ROOT)/src/Providers/UNIXProviders/SwitchVirtualInterface \
\
	$(ROOT)/src/Providers/UNIXProviders/IPLoopback \
\
	$(ROOT)/src/Providers/UNIXProviders/BGPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/SwitchPort \
\
	$(ROOT)/src/Providers/UNIXProviders/DNSProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LAGPort8023ad \




DIR = Providers/UNIXProviders/ProvidesEndpoint
include $(ROOT)/mak/config.mak
LIBRARY = UNIX_ProvidesEndpointProvider
EXTRA_INCLUDES += -I/usr/local/include -I./..

DEFINES +=  -DPROVIDER_LIB_NS="UNIX_ProvidesEndpointLib" -DPROVIDER_LIB_NS_BEGIN="namespace UNIX_ProvidesEndpointLib {"

SOURCES = \
	../CIMHelper.cpp \
	UNIX_ProvidesEndpoint.cpp \
	UNIX_ProvidesEndpointProvider.cpp \
	UNIX_ProvidesEndpointMain.cpp

ifeq ($(OS), aix)
	SOURCES += UNIX_ProvidesEndpoint_AIX.cpp
endif
ifeq ($(OS), darwin)
	SOURCES += UNIX_ProvidesEndpoint_DARWIN.cpp
endif
ifeq ($(OS), freebsd)
	SOURCES += UNIX_ProvidesEndpoint_FREEBSD.cpp
endif
ifeq ($(OS), hpux)
	SOURCES += UNIX_ProvidesEndpoint_HPUX.cpp
endif
ifeq ($(OS), linux)
	SOURCES += UNIX_ProvidesEndpoint_LINUX.cpp
endif
ifeq ($(OS), solaris)
	SOURCES += UNIX_ProvidesEndpoint_SOLARIS.cpp
endif
ifeq ($(OS), tru64)
	SOURCES += UNIX_ProvidesEndpoint_TRU64.cpp
endif
ifeq ($(OS), vms)
	SOURCES += UNIX_ProvidesEndpoint_VMS.cpp
endif
ifeq ($(OS), win32)
	SOURCES += UNIX_ProvidesEndpoint_WIN32.cpp
endif
ifeq ($(OS), zos)
	SOURCES += UNIX_ProvidesEndpoint_ZOS.cpp
endif
ifeq (, $(filter aix,darwin,freebsd,hpux,linux,solaris,tru64,vms,win32,zos $(OS)))

else
	SOURCES += UNIX_ProvidesEndpoint_STUB.cpp
endif

LIBRARIES += \
	UNIX_FibreProtocolServiceProvider\
	UNIX_WakeUpServiceProvider\
	UNIX_VirtualSystemSnapshotServiceProvider\
	UNIX_ResourcePoolConfigurationServiceProvider\
	UNIX_FileSystemConfigurationServiceProvider\
	UNIX_HelpServiceProvider\
	UNIX_StorageRelocationServiceProvider\
	UNIX_MPLSServiceProvider\
	UNIX_PolicyActivationServiceProvider\
	UNIX_SCSIPathConfigurationServiceProvider\
	UNIX_BIOSServiceProvider\
	UNIX_PowerManagementServiceProvider\
	UNIX_NetworkPortConfigurationServiceProvider\
	UNIX_WiFiPortConfigurationServiceProvider\
	UNIX_VRFConfigurationServiceProvider\
	UNIX_ReplicationServiceProvider\
	UNIX_AccountManagementServiceProvider\
	UNIX_VerificationServiceProvider\
	UNIX_CertificateAuthorityProvider\
	UNIX_NotaryProvider\
	UNIX_KeyBasedCredentialManagementServiceProvider\
	UNIX_CertificateManagementServiceProvider\
	UNIX_KerberosKeyDistributionCenterProvider\
	UNIX_PublicKeyManagementServiceProvider\
	UNIX_SharedSecretServiceProvider\
	UNIX_IdentityManagementServiceProvider\
	UNIX_StorageHardwareIDManagementServiceProvider\
	UNIX_AuthorizationServiceProvider\
	UNIX_PrivilegeManagementServiceProvider\
	UNIX_RoleBasedAuthorizationServiceProvider\
	UNIX_AccessControlServiceProvider\
	UNIX_WBEMServerProvider\
	UNIX_LaunchInContextServiceProvider\
	UNIX_VirtualSystemManagementServiceProvider\
	UNIX_MetricServiceProvider\
	UNIX_StorageNameBindingServiceProvider\
	UNIX_ZoneServiceProvider\
	UNIX_ControllerConfigurationServiceProvider\
	UNIX_GroupMaskingMappingServiceProvider\
	UNIX_DatabaseServiceProvider\
	UNIX_DiskPartitionConfigurationServiceProvider\
	UNIX_ConfigurationReportingServiceProvider\
	UNIX_PowerTopologyServiceProvider\
	UNIX_NetworkPolicyServiceProvider\
	UNIX_BasicExecutionServiceProvider\
	UNIX_SpareConfigurationServiceProvider\
	UNIX_StorageElementCompositionServiceProvider\
	UNIX_OpaqueManagementDataServiceProvider\
	UNIX_FingerprintMatchingServiceProvider\
	UNIX_ProtocolServiceProvider\
	UNIX_WBEMProtocolServiceProvider\
	UNIX_TierServiceProvider\
	UNIX_TierPolicyServiceProvider\
	UNIX_IndicationServiceProvider\
	UNIX_FileImportServiceProvider\
	UNIX_VTLStatisticalDataServiceProvider\
	UNIX_DropThresholdCalculationServiceProvider\
	UNIX_TokenBucketMeterServiceProvider\
	UNIX_EWMAMeterServiceProvider\
	UNIX_AverageRateMeterServiceProvider\
	UNIX_ToSMarkerServiceProvider\
	UNIX_Priority8021QMarkerServiceProvider\
	UNIX_DSCPMarkerServiceProvider\
	UNIX_PreambleMarkerServiceProvider\
	UNIX_ClassifierServiceProvider\
	UNIX_ClassifierElementProvider\
	UNIX_PacketSchedulingServiceProvider\
	UNIX_NonWorkConservingSchedulingServiceProvider\
	UNIX_REDDropperServiceProvider\
	UNIX_HeadTailDropperProvider\
	UNIX_WeightedREDDropperServiceProvider\
	UNIX_QueuingServiceProvider\
	UNIX_BootServiceProvider\
	UNIX_AFServiceProvider\
	UNIX_EFServiceProvider\
	UNIX_FlowServiceProvider\
	UNIX_Hdr8021PServiceProvider\
	UNIX_PrecedenceServiceProvider\
	UNIX_PrintServiceProvider\
	UNIX_TimeServiceProvider\
	UNIX_SoftwareInstallationServiceProvider\
	UNIX_VLANServiceProvider\
	UNIX_Specific802dot1QVLANServiceProvider\
	UNIX_PowerUtilizationManagementServiceProvider\
	UNIX_ClusteringServiceProvider\
	UNIX_SharedDeviceManagementServiceProvider\
	UNIX_BatchServiceProvider\
	UNIX_iSCSIConfigurationServiceProvider\
	UNIX_OOBAlertServiceProvider\
	UNIX_StorageConfigurationServiceProvider\
	UNIX_IPConfigurationServiceProvider\
	UNIX_VirtualSystemMigrationServiceProvider\
	UNIX_MPLSCrossConnectProvider\
	UNIX_PlatformWatchdogServiceProvider\
	UNIX_FCHBADiagnosticTestProvider\
	UNIX_RAIDDiagnosticTestProvider\
	UNIX_CPUDiagnosticTestProvider\
	UNIX_EthernetNICDiagnosticTestProvider\
	UNIX_OpticalDriveDiagnosticTestProvider\
	UNIX_OpticalDriveDiagnosticSettingDataProvider\
	UNIX_DiskDriveDiagnosticTestProvider\
	UNIX_IBSubnetManagerProvider\
	UNIX_ObjectManagerProvider\
	UNIX_ObjectManagerAdapterProvider\
	UNIX_ProviderObjectManagerAdapterProvider\
	UNIX_ProtocolAdapterProvider\
	UNIX_FileSystemStatisticsServiceProvider\
	UNIX_BlockStatisticsServiceProvider\
	UNIX_USBRedirectionServiceProvider\
	UNIX_TextRedirectionServiceProvider\
	UNIX_BGPServiceProvider\
	UNIX_OSPFServiceProvider\
	UNIX_NATServiceProvider\
	UNIX_TransparentBridgingServiceProvider\
	UNIX_SourceRoutingServiceProvider\
	UNIX_SpanningTreeServiceProvider\
	UNIX_SwitchServiceProvider\
	UNIX_FileExportServiceProvider\
	UNIX_DHCPProtocolEndpointProvider\
	UNIX_SSHProtocolEndpointProvider\
	UNIX_SCSIProtocolEndpointProvider\
	UNIX_iSCSIProtocolEndpointProvider\
	UNIX_CLPProtocolEndpointProvider\
	UNIX_IPXProtocolEndpointProvider\
	UNIX_IPsecSAEndpointProvider\
	UNIX_IKESAEndpointProvider\
	UNIX_LANEndpointProvider\
	UNIX_WiFiEndpointProvider\
	UNIX_MPLSProtocolEndpointProvider\
	UNIX_WirelessLANEndpointProvider\
	UNIX_UDPProtocolEndpointProvider\
	UNIX_TCPProtocolEndpointProvider\
	UNIX_OSPFVirtualInterfaceProvider\
	UNIX_OSPFProtocolEndpointProvider\
	UNIX_VLANEndpointProvider\
	UNIX_LinkAggregator8023adProvider\
	UNIX_ATAProtocolEndpointProvider\
	UNIX_IPEncapsulationInterfaceProvider\
	UNIX_IPSubinterfaceProvider\
	UNIX_SwitchVirtualInterfaceProvider\
	UNIX_IPLoopbackProvider\
	UNIX_BGPProtocolEndpointProvider\
	UNIX_SwitchPortProvider\
	UNIX_DNSProtocolEndpointProvider\
	UNIX_LAGPort8023adProvider

EXTRA_LIBRARIES = \
	-lpegprovider \
	-lpegclient \
	-lpegcommon \
	-lpegquerycommon \
	-lpegqueryexpression \
	-lpegcql \
	-lpegwql \
	-lpthread \
	-lutil \
	-lkvm

include $(ROOT)/mak/dynamic-library.mak





