#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////
#//
#//%/////////////////////////////////////////////////////////////////////////


ROOT = ../../../..
DIRS = \
	$(ROOT)/src/Providers/UNIXProviders/MPLSLSP \
\
	$(ROOT)/src/Providers/UNIXProviders/CommonDatabase \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSTunnel \
\
	$(ROOT)/src/Providers/UNIXProviders/ReplicationEntity \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintQueue \
\
	$(ROOT)/src/Providers/UNIXProviders/JobQueue \
\
	$(ROOT)/src/Providers/UNIXProviders/ReusablePolicyContainer \
\
	$(ROOT)/src/Providers/UNIXProviders/PolicyRepository \
\
	$(ROOT)/src/Providers/UNIXProviders/AutonomousSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/RoutingProtocolDomain \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFArea \
\
	$(ROOT)/src/Providers/UNIXProviders/Network \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANNetwork \
\
	$(ROOT)/src/Providers/UNIXProviders/TierDomain \
\
	$(ROOT)/src/Providers/UNIXProviders/ApplicationSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageLibrary \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualComputerSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/Cluster \
\
	$(ROOT)/src/Providers/UNIXProviders/ComputerSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIArbitraryLogicalUnit \
\
	$(ROOT)/src/Providers/UNIXProviders/Button \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerSupply \
\
	$(ROOT)/src/Providers/UNIXProviders/UninterruptiblePowerSupply \
\
	$(ROOT)/src/Providers/UNIXProviders/Battery \
\
	$(ROOT)/src/Providers/UNIXProviders/TapeDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/CDROMDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/WORMDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/DVDDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/DisketteDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/MagnetoOpticalDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/USBDevice \
\
	$(ROOT)/src/Providers/UNIXProviders/USBHub \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerConnectionPoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LabelReader \
\
	$(ROOT)/src/Providers/UNIXProviders/LogicalDisk \
\
	$(ROOT)/src/Providers/UNIXProviders/Snapshot \
\
	$(ROOT)/src/Providers/UNIXProviders/VTOCDiskPartition \
\
	$(ROOT)/src/Providers/UNIXProviders/GPTDiskPartition \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskPartition \
\
	$(ROOT)/src/Providers/UNIXProviders/TapePartition \
\
	$(ROOT)/src/Providers/UNIXProviders/CompositeExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtectedSpaceExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/PhysicalExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseSegment \
\
	$(ROOT)/src/Providers/UNIXProviders/AggregatePExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/VolumeSet \
\
	$(ROOT)/src/Providers/UNIXProviders/OpaqueManagementData \
\
	$(ROOT)/src/Providers/UNIXProviders/AggregatePSExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/CacheMemory \
\
	$(ROOT)/src/Providers/UNIXProviders/VolatileStorage \
\
	$(ROOT)/src/Providers/UNIXProviders/NonVolatileStorage \
\
	$(ROOT)/src/Providers/UNIXProviders/Printer \
\
	$(ROOT)/src/Providers/UNIXProviders/CurrentSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/TemperatureSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/VoltageSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/Tachometer \
\
	$(ROOT)/src/Providers/UNIXProviders/MultiStateSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/BinarySensor \
\
	$(ROOT)/src/Providers/UNIXProviders/DiscreteSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/CableModem \
\
	$(ROOT)/src/Providers/UNIXProviders/ADSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/VDSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/HDSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/SDSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/Unimodem \
\
	$(ROOT)/src/Providers/UNIXProviders/ISDNModem \
\
	$(ROOT)/src/Providers/UNIXProviders/Keyboard \
\
	$(ROOT)/src/Providers/UNIXProviders/PointingDevice \
\
	$(ROOT)/src/Providers/UNIXProviders/DesktopMonitor \
\
	$(ROOT)/src/Providers/UNIXProviders/FlatPanel \
\
	$(ROOT)/src/Providers/UNIXProviders/Processor \
\
	$(ROOT)/src/Providers/UNIXProviders/VideoHead \
\
	$(ROOT)/src/Providers/UNIXProviders/FingerprintReader \
\
	$(ROOT)/src/Providers/UNIXProviders/Door \
\
	$(ROOT)/src/Providers/UNIXProviders/SmartCard \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPort \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiPort \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetPort \
\
	$(ROOT)/src/Providers/UNIXProviders/LLDPEthernetPort \
\
	$(ROOT)/src/Providers/UNIXProviders/DataCenterEthernetPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SASPort \
\
	$(ROOT)/src/Providers/UNIXProviders/IBPort \
\
	$(ROOT)/src/Providers/UNIXProviders/FCPort \
\
	$(ROOT)/src/Providers/UNIXProviders/WirelessPort \
\
	$(ROOT)/src/Providers/UNIXProviders/TokenRingPort \
\
	$(ROOT)/src/Providers/UNIXProviders/DAPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SerialPort \
\
	$(ROOT)/src/Providers/UNIXProviders/ATAPort \
\
	$(ROOT)/src/Providers/UNIXProviders/USBPort \
\
	$(ROOT)/src/Providers/UNIXProviders/PCIPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SPIPort \
\
	$(ROOT)/src/Providers/UNIXProviders/ParallelPort \
\
	$(ROOT)/src/Providers/UNIXProviders/FibrePort \
\
	$(ROOT)/src/Providers/UNIXProviders/Watchdog \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/TokenRingAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/FibreChannelAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicatorLED \
\
	$(ROOT)/src/Providers/UNIXProviders/ElectricalSwitch \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolController \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIProtocolController \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiRadio \
\
	$(ROOT)/src/Providers/UNIXProviders/InterLibraryPort \
\
	$(ROOT)/src/Providers/UNIXProviders/LimitedAccessPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SmartCardReader \
\
	$(ROOT)/src/Providers/UNIXProviders/PCIBridge \
\
	$(ROOT)/src/Providers/UNIXProviders/PCIeSwitch \
\
	$(ROOT)/src/Providers/UNIXProviders/PortController \
\
	$(ROOT)/src/Providers/UNIXProviders/IBPortController \
\
	$(ROOT)/src/Providers/UNIXProviders/ParallelController \
\
	$(ROOT)/src/Providers/UNIXProviders/InfraredController \
\
	$(ROOT)/src/Providers/UNIXProviders/ManagementController \
\
	$(ROOT)/src/Providers/UNIXProviders/SSAController \
\
	$(ROOT)/src/Providers/UNIXProviders/AGPVideoController \
\
	$(ROOT)/src/Providers/UNIXProviders/PCVideoController \
\
	$(ROOT)/src/Providers/UNIXProviders/SerialController \
\
	$(ROOT)/src/Providers/UNIXProviders/DisplayController \
\
	$(ROOT)/src/Providers/UNIXProviders/AGPVideoDisplayController \
\
	$(ROOT)/src/Providers/UNIXProviders/USBController \
\
	$(ROOT)/src/Providers/UNIXProviders/IDEController \
\
	$(ROOT)/src/Providers/UNIXProviders/PCMCIAController \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIController \
\
	$(ROOT)/src/Providers/UNIXProviders/ESCONController \
\
	$(ROOT)/src/Providers/UNIXProviders/DeviceTray \
\
	$(ROOT)/src/Providers/UNIXProviders/PassThroughModule \
\
	$(ROOT)/src/Providers/UNIXProviders/AlarmDevice \
\
	$(ROOT)/src/Providers/UNIXProviders/Fan \
\
	$(ROOT)/src/Providers/UNIXProviders/Refrigeration \
\
	$(ROOT)/src/Providers/UNIXProviders/HeatPipe \
\
	$(ROOT)/src/Providers/UNIXProviders/TPM \
\
	$(ROOT)/src/Providers/UNIXProviders/Scanner \
\
	$(ROOT)/src/Providers/UNIXProviders/Provider \
\
	$(ROOT)/src/Providers/UNIXProviders/IRQ \
\
	$(ROOT)/src/Providers/UNIXProviders/PortResource \
\
	$(ROOT)/src/Providers/UNIXProviders/MemoryResource \
\
	$(ROOT)/src/Providers/UNIXProviders/DMA \
\
	$(ROOT)/src/Providers/UNIXProviders/NFSShare \
\
	$(ROOT)/src/Providers/UNIXProviders/CIFSShare \
\
	$(ROOT)/src/Providers/UNIXProviders/MessageLog \
\
	$(ROOT)/src/Providers/UNIXProviders/DiagnosticLog \
\
	$(ROOT)/src/Providers/UNIXProviders/DiagnosticsLog \
\
	$(ROOT)/src/Providers/UNIXProviders/FibreProtocolService \
\
	$(ROOT)/src/Providers/UNIXProviders/WakeUpService \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemSnapshotService \
\
	$(ROOT)/src/Providers/UNIXProviders/ResourcePoolConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/HelpService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageRelocationService \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSService \
\
	$(ROOT)/src/Providers/UNIXProviders/PolicyActivationService \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIPathConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/BIOSService \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPortConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiPortConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/VRFConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/ReplicationService \
\
	$(ROOT)/src/Providers/UNIXProviders/AccountManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/VerificationService \
\
	$(ROOT)/src/Providers/UNIXProviders/CertificateAuthority \
\
	$(ROOT)/src/Providers/UNIXProviders/Notary \
\
	$(ROOT)/src/Providers/UNIXProviders/KeyBasedCredentialManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/CertificateManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/KerberosKeyDistributionCenter \
\
	$(ROOT)/src/Providers/UNIXProviders/PublicKeyManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/SharedSecretService \
\
	$(ROOT)/src/Providers/UNIXProviders/IdentityManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageHardwareIDManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/AuthorizationService \
\
	$(ROOT)/src/Providers/UNIXProviders/PrivilegeManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/RoleBasedAuthorizationService \
\
	$(ROOT)/src/Providers/UNIXProviders/AccessControlService \
\
	$(ROOT)/src/Providers/UNIXProviders/WBEMServer \
\
	$(ROOT)/src/Providers/UNIXProviders/LaunchInContextService \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/MetricService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageNameBindingService \
\
	$(ROOT)/src/Providers/UNIXProviders/ZoneService \
\
	$(ROOT)/src/Providers/UNIXProviders/ControllerConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/GroupMaskingMappingService \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseService \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskPartitionConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/ConfigurationReportingService \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerTopologyService \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPolicyService \
\
	$(ROOT)/src/Providers/UNIXProviders/BasicExecutionService \
\
	$(ROOT)/src/Providers/UNIXProviders/SpareConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageElementCompositionService \
\
	$(ROOT)/src/Providers/UNIXProviders/OpaqueManagementDataService \
\
	$(ROOT)/src/Providers/UNIXProviders/FingerprintMatchingService \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolService \
\
	$(ROOT)/src/Providers/UNIXProviders/WBEMProtocolService \
\
	$(ROOT)/src/Providers/UNIXProviders/TierService \
\
	$(ROOT)/src/Providers/UNIXProviders/TierPolicyService \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicationService \
\
	$(ROOT)/src/Providers/UNIXProviders/FileImportService \
\
	$(ROOT)/src/Providers/UNIXProviders/VTLStatisticalDataService \
\
	$(ROOT)/src/Providers/UNIXProviders/DropThresholdCalculationService \
\
	$(ROOT)/src/Providers/UNIXProviders/TokenBucketMeterService \
\
	$(ROOT)/src/Providers/UNIXProviders/EWMAMeterService \
\
	$(ROOT)/src/Providers/UNIXProviders/AverageRateMeterService \
\
	$(ROOT)/src/Providers/UNIXProviders/ToSMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/Priority8021QMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/DSCPMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/PreambleMarkerService \
\
	$(ROOT)/src/Providers/UNIXProviders/ClassifierService \
\
	$(ROOT)/src/Providers/UNIXProviders/ClassifierElement \
\
	$(ROOT)/src/Providers/UNIXProviders/PacketSchedulingService \
\
	$(ROOT)/src/Providers/UNIXProviders/NonWorkConservingSchedulingService \
\
	$(ROOT)/src/Providers/UNIXProviders/REDDropperService \
\
	$(ROOT)/src/Providers/UNIXProviders/HeadTailDropper \
\
	$(ROOT)/src/Providers/UNIXProviders/WeightedREDDropperService \
\
	$(ROOT)/src/Providers/UNIXProviders/QueuingService \
\
	$(ROOT)/src/Providers/UNIXProviders/BootService \
\
	$(ROOT)/src/Providers/UNIXProviders/AFService \
\
	$(ROOT)/src/Providers/UNIXProviders/EFService \
\
	$(ROOT)/src/Providers/UNIXProviders/FlowService \
\
	$(ROOT)/src/Providers/UNIXProviders/Hdr8021PService \
\
	$(ROOT)/src/Providers/UNIXProviders/PrecedenceService \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintService \
\
	$(ROOT)/src/Providers/UNIXProviders/TimeService \
\
	$(ROOT)/src/Providers/UNIXProviders/SoftwareInstallationService \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANService \
\
	$(ROOT)/src/Providers/UNIXProviders/Specific802dot1QVLANService \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerUtilizationManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/ClusteringService \
\
	$(ROOT)/src/Providers/UNIXProviders/SharedDeviceManagementService \
\
	$(ROOT)/src/Providers/UNIXProviders/BatchService \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/OOBAlertService \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/IPConfigurationService \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemMigrationService \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSCrossConnect \
\
	$(ROOT)/src/Providers/UNIXProviders/PlatformWatchdogService \
\
	$(ROOT)/src/Providers/UNIXProviders/FCHBADiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/RAIDDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/CPUDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetNICDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/OpticalDriveDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/OpticalDriveDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDriveDiagnosticTest \
\
	$(ROOT)/src/Providers/UNIXProviders/IBSubnetManager \
\
	$(ROOT)/src/Providers/UNIXProviders/ObjectManager \
\
	$(ROOT)/src/Providers/UNIXProviders/ObjectManagerAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/ProviderObjectManagerAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemStatisticsService \
\
	$(ROOT)/src/Providers/UNIXProviders/BlockStatisticsService \
\
	$(ROOT)/src/Providers/UNIXProviders/USBRedirectionService \
\
	$(ROOT)/src/Providers/UNIXProviders/TextRedirectionService \
\
	$(ROOT)/src/Providers/UNIXProviders/BGPService \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFService \
\
	$(ROOT)/src/Providers/UNIXProviders/NATService \
\
	$(ROOT)/src/Providers/UNIXProviders/TransparentBridgingService \
\
	$(ROOT)/src/Providers/UNIXProviders/SourceRoutingService \
\
	$(ROOT)/src/Providers/UNIXProviders/SpanningTreeService \
\
	$(ROOT)/src/Providers/UNIXProviders/SwitchService \
\
	$(ROOT)/src/Providers/UNIXProviders/FileExportService \
\
	$(ROOT)/src/Providers/UNIXProviders/OperatingSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/SWRFile \
\
	$(ROOT)/src/Providers/UNIXProviders/SWRPEP \
\
	$(ROOT)/src/Providers/UNIXProviders/SWRDatabase \
\
	$(ROOT)/src/Providers/UNIXProviders/ProviderLibrary \
\
	$(ROOT)/src/Providers/UNIXProviders/ClusteringSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/CredentialManagementSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/USBRedirectionSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/IPNetworkConnection \
\
	$(ROOT)/src/Providers/UNIXProviders/PolicyTransferServiceAccessPoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LaunchInContextSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/RemotePort \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSTunnelHop \
\
	$(ROOT)/src/Providers/UNIXProviders/SoftwareIdentityResource \
\
	$(ROOT)/src/Providers/UNIXProviders/KVMRedirectionSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/DHCPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/SSHProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/CLPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IPXProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IPsecSAEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IKESAEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LANEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/WirelessLANEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/UDPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/TCPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFVirtualInterface \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LinkAggregator8023ad \
\
	$(ROOT)/src/Providers/UNIXProviders/ATAProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/IPEncapsulationInterface \
\
	$(ROOT)/src/Providers/UNIXProviders/IPSubinterface \
\
	$(ROOT)/src/Providers/UNIXProviders/SwitchVirtualInterface \
\
	$(ROOT)/src/Providers/UNIXProviders/IPLoopback \
\
	$(ROOT)/src/Providers/UNIXProviders/BGPProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/SwitchPort \
\
	$(ROOT)/src/Providers/UNIXProviders/DNSProtocolEndpoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LAGPort8023ad \
\
	$(ROOT)/src/Providers/UNIXProviders/BatchSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/TextRedirectionSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/MediaRedirectionSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/ServiceAccessURI \
\
	$(ROOT)/src/Providers/UNIXProviders/ObjectManagerCommunicationMechanism \
\
	$(ROOT)/src/Providers/UNIXProviders/CIMXMLCommunicationMechanism \
\
	$(ROOT)/src/Providers/UNIXProviders/VLAN \
\
	$(ROOT)/src/Providers/UNIXProviders/BootSAP \
\
	$(ROOT)/src/Providers/UNIXProviders/Process \
\
	$(ROOT)/src/Providers/UNIXProviders/ProcessorCore \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSISession \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIConnection \
\
	$(ROOT)/src/Providers/UNIXProviders/HardwareThread \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseStorageArea \
\
	$(ROOT)/src/Providers/UNIXProviders/LocalFileSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/RemoteFileSystem \
\
	$(ROOT)/src/Providers/UNIXProviders/NFS \
\
	$(ROOT)/src/Providers/UNIXProviders/Thread \
\
	$(ROOT)/src/Providers/UNIXProviders/Account \
\
	$(ROOT)/src/Providers/UNIXProviders/StoragePool \




DIR = Providers/UNIXProviders/ReplicaPoolForStorage
include $(ROOT)/mak/config.mak
LIBRARY = UNIX_ReplicaPoolForStorageProvider
EXTRA_INCLUDES += -I/usr/local/include -I./..

DEFINES +=  -DPROVIDER_LIB_NS="UNIX_ReplicaPoolForStorageLib" -DPROVIDER_LIB_NS_BEGIN="namespace UNIX_ReplicaPoolForStorageLib {"

SOURCES = \
	../CIMHelper.cpp \
	UNIX_ReplicaPoolForStorage.cpp \
	UNIX_ReplicaPoolForStorageProvider.cpp \
	UNIX_ReplicaPoolForStorageMain.cpp

ifeq ($(OS), aix)
	SOURCES += UNIX_ReplicaPoolForStorage_AIX.cpp
endif
ifeq ($(OS), darwin)
	SOURCES += UNIX_ReplicaPoolForStorage_DARWIN.cpp
endif
ifeq ($(OS), freebsd)
	SOURCES += UNIX_ReplicaPoolForStorage_FREEBSD.cpp
endif
ifeq ($(OS), hpux)
	SOURCES += UNIX_ReplicaPoolForStorage_HPUX.cpp
endif
ifeq ($(OS), linux)
	SOURCES += UNIX_ReplicaPoolForStorage_LINUX.cpp
endif
ifeq ($(OS), solaris)
	SOURCES += UNIX_ReplicaPoolForStorage_SOLARIS.cpp
endif
ifeq ($(OS), tru64)
	SOURCES += UNIX_ReplicaPoolForStorage_TRU64.cpp
endif
ifeq ($(OS), vms)
	SOURCES += UNIX_ReplicaPoolForStorage_VMS.cpp
endif
ifeq ($(OS), win32)
	SOURCES += UNIX_ReplicaPoolForStorage_WIN32.cpp
endif
ifeq ($(OS), zos)
	SOURCES += UNIX_ReplicaPoolForStorage_ZOS.cpp
endif
ifeq (, $(filter aix,darwin,freebsd,hpux,linux,solaris,tru64,vms,win32,zos $(OS)))

else
	SOURCES += UNIX_ReplicaPoolForStorage_STUB.cpp
endif

LIBRARIES += \
	UNIX_MPLSLSPProvider\
	UNIX_CommonDatabaseProvider\
	UNIX_MPLSTunnelProvider\
	UNIX_ReplicationEntityProvider\
	UNIX_PrintQueueProvider\
	UNIX_JobQueueProvider\
	UNIX_ReusablePolicyContainerProvider\
	UNIX_PolicyRepositoryProvider\
	UNIX_AutonomousSystemProvider\
	UNIX_RoutingProtocolDomainProvider\
	UNIX_OSPFAreaProvider\
	UNIX_NetworkProvider\
	UNIX_VLANNetworkProvider\
	UNIX_TierDomainProvider\
	UNIX_ApplicationSystemProvider\
	UNIX_DatabaseSystemProvider\
	UNIX_StorageLibraryProvider\
	UNIX_VirtualComputerSystemProvider\
	UNIX_ClusterProvider\
	UNIX_ComputerSystemProvider\
	UNIX_SCSIArbitraryLogicalUnitProvider\
	UNIX_ButtonProvider\
	UNIX_PowerSupplyProvider\
	UNIX_UninterruptiblePowerSupplyProvider\
	UNIX_BatteryProvider\
	UNIX_TapeDriveProvider\
	UNIX_CDROMDriveProvider\
	UNIX_WORMDriveProvider\
	UNIX_DiskDriveProvider\
	UNIX_DVDDriveProvider\
	UNIX_DisketteDriveProvider\
	UNIX_MagnetoOpticalDriveProvider\
	UNIX_USBDeviceProvider\
	UNIX_USBHubProvider\
	UNIX_PowerConnectionPointProvider\
	UNIX_LabelReaderProvider\
	UNIX_LogicalDiskProvider\
	UNIX_SnapshotProvider\
	UNIX_VTOCDiskPartitionProvider\
	UNIX_GPTDiskPartitionProvider\
	UNIX_DiskPartitionProvider\
	UNIX_TapePartitionProvider\
	UNIX_CompositeExtentProvider\
	UNIX_ProtectedSpaceExtentProvider\
	UNIX_PhysicalExtentProvider\
	UNIX_DatabaseSegmentProvider\
	UNIX_AggregatePExtentProvider\
	UNIX_VolumeSetProvider\
	UNIX_OpaqueManagementDataProvider\
	UNIX_AggregatePSExtentProvider\
	UNIX_CacheMemoryProvider\
	UNIX_VolatileStorageProvider\
	UNIX_NonVolatileStorageProvider\
	UNIX_PrinterProvider\
	UNIX_CurrentSensorProvider\
	UNIX_TemperatureSensorProvider\
	UNIX_VoltageSensorProvider\
	UNIX_TachometerProvider\
	UNIX_MultiStateSensorProvider\
	UNIX_BinarySensorProvider\
	UNIX_DiscreteSensorProvider\
	UNIX_CableModemProvider\
	UNIX_ADSLModemProvider\
	UNIX_VDSLModemProvider\
	UNIX_HDSLModemProvider\
	UNIX_SDSLModemProvider\
	UNIX_UnimodemProvider\
	UNIX_ISDNModemProvider\
	UNIX_KeyboardProvider\
	UNIX_PointingDeviceProvider\
	UNIX_DesktopMonitorProvider\
	UNIX_FlatPanelProvider\
	UNIX_ProcessorProvider\
	UNIX_VideoHeadProvider\
	UNIX_FingerprintReaderProvider\
	UNIX_DoorProvider\
	UNIX_SmartCardProvider\
	UNIX_NetworkPortProvider\
	UNIX_WiFiPortProvider\
	UNIX_EthernetPortProvider\
	UNIX_LLDPEthernetPortProvider\
	UNIX_DataCenterEthernetPortProvider\
	UNIX_SASPortProvider\
	UNIX_IBPortProvider\
	UNIX_FCPortProvider\
	UNIX_WirelessPortProvider\
	UNIX_TokenRingPortProvider\
	UNIX_DAPortProvider\
	UNIX_SerialPortProvider\
	UNIX_ATAPortProvider\
	UNIX_USBPortProvider\
	UNIX_PCIPortProvider\
	UNIX_SPIPortProvider\
	UNIX_ParallelPortProvider\
	UNIX_FibrePortProvider\
	UNIX_WatchdogProvider\
	UNIX_EthernetAdapterProvider\
	UNIX_TokenRingAdapterProvider\
	UNIX_FibreChannelAdapterProvider\
	UNIX_IndicatorLEDProvider\
	UNIX_ElectricalSwitchProvider\
	UNIX_ProtocolControllerProvider\
	UNIX_SCSIProtocolControllerProvider\
	UNIX_WiFiRadioProvider\
	UNIX_InterLibraryPortProvider\
	UNIX_LimitedAccessPortProvider\
	UNIX_SmartCardReaderProvider\
	UNIX_PCIBridgeProvider\
	UNIX_PCIeSwitchProvider\
	UNIX_PortControllerProvider\
	UNIX_IBPortControllerProvider\
	UNIX_ParallelControllerProvider\
	UNIX_InfraredControllerProvider\
	UNIX_ManagementControllerProvider\
	UNIX_SSAControllerProvider\
	UNIX_AGPVideoControllerProvider\
	UNIX_PCVideoControllerProvider\
	UNIX_SerialControllerProvider\
	UNIX_DisplayControllerProvider\
	UNIX_AGPVideoDisplayControllerProvider\
	UNIX_USBControllerProvider\
	UNIX_IDEControllerProvider\
	UNIX_PCMCIAControllerProvider\
	UNIX_SCSIControllerProvider\
	UNIX_ESCONControllerProvider\
	UNIX_DeviceTrayProvider\
	UNIX_PassThroughModuleProvider\
	UNIX_AlarmDeviceProvider\
	UNIX_FanProvider\
	UNIX_RefrigerationProvider\
	UNIX_HeatPipeProvider\
	UNIX_TPMProvider\
	UNIX_ScannerProvider\
	UNIX_ProviderProvider\
	UNIX_IRQProvider\
	UNIX_PortResourceProvider\
	UNIX_MemoryResourceProvider\
	UNIX_DMAProvider\
	UNIX_NFSShareProvider\
	UNIX_CIFSShareProvider\
	UNIX_MessageLogProvider\
	UNIX_DiagnosticLogProvider\
	UNIX_DiagnosticsLogProvider\
	UNIX_FibreProtocolServiceProvider\
	UNIX_WakeUpServiceProvider\
	UNIX_VirtualSystemSnapshotServiceProvider\
	UNIX_ResourcePoolConfigurationServiceProvider\
	UNIX_FileSystemConfigurationServiceProvider\
	UNIX_HelpServiceProvider\
	UNIX_StorageRelocationServiceProvider\
	UNIX_MPLSServiceProvider\
	UNIX_PolicyActivationServiceProvider\
	UNIX_SCSIPathConfigurationServiceProvider\
	UNIX_BIOSServiceProvider\
	UNIX_PowerManagementServiceProvider\
	UNIX_NetworkPortConfigurationServiceProvider\
	UNIX_WiFiPortConfigurationServiceProvider\
	UNIX_VRFConfigurationServiceProvider\
	UNIX_ReplicationServiceProvider\
	UNIX_AccountManagementServiceProvider\
	UNIX_VerificationServiceProvider\
	UNIX_CertificateAuthorityProvider\
	UNIX_NotaryProvider\
	UNIX_KeyBasedCredentialManagementServiceProvider\
	UNIX_CertificateManagementServiceProvider\
	UNIX_KerberosKeyDistributionCenterProvider\
	UNIX_PublicKeyManagementServiceProvider\
	UNIX_SharedSecretServiceProvider\
	UNIX_IdentityManagementServiceProvider\
	UNIX_StorageHardwareIDManagementServiceProvider\
	UNIX_AuthorizationServiceProvider\
	UNIX_PrivilegeManagementServiceProvider\
	UNIX_RoleBasedAuthorizationServiceProvider\
	UNIX_AccessControlServiceProvider\
	UNIX_WBEMServerProvider\
	UNIX_LaunchInContextServiceProvider\
	UNIX_VirtualSystemManagementServiceProvider\
	UNIX_MetricServiceProvider\
	UNIX_StorageNameBindingServiceProvider\
	UNIX_ZoneServiceProvider\
	UNIX_ControllerConfigurationServiceProvider\
	UNIX_GroupMaskingMappingServiceProvider\
	UNIX_DatabaseServiceProvider\
	UNIX_DiskPartitionConfigurationServiceProvider\
	UNIX_ConfigurationReportingServiceProvider\
	UNIX_PowerTopologyServiceProvider\
	UNIX_NetworkPolicyServiceProvider\
	UNIX_BasicExecutionServiceProvider\
	UNIX_SpareConfigurationServiceProvider\
	UNIX_StorageElementCompositionServiceProvider\
	UNIX_OpaqueManagementDataServiceProvider\
	UNIX_FingerprintMatchingServiceProvider\
	UNIX_ProtocolServiceProvider\
	UNIX_WBEMProtocolServiceProvider\
	UNIX_TierServiceProvider\
	UNIX_TierPolicyServiceProvider\
	UNIX_IndicationServiceProvider\
	UNIX_FileImportServiceProvider\
	UNIX_VTLStatisticalDataServiceProvider\
	UNIX_DropThresholdCalculationServiceProvider\
	UNIX_TokenBucketMeterServiceProvider\
	UNIX_EWMAMeterServiceProvider\
	UNIX_AverageRateMeterServiceProvider\
	UNIX_ToSMarkerServiceProvider\
	UNIX_Priority8021QMarkerServiceProvider\
	UNIX_DSCPMarkerServiceProvider\
	UNIX_PreambleMarkerServiceProvider\
	UNIX_ClassifierServiceProvider\
	UNIX_ClassifierElementProvider\
	UNIX_PacketSchedulingServiceProvider\
	UNIX_NonWorkConservingSchedulingServiceProvider\
	UNIX_REDDropperServiceProvider\
	UNIX_HeadTailDropperProvider\
	UNIX_WeightedREDDropperServiceProvider\
	UNIX_QueuingServiceProvider\
	UNIX_BootServiceProvider\
	UNIX_AFServiceProvider\
	UNIX_EFServiceProvider\
	UNIX_FlowServiceProvider\
	UNIX_Hdr8021PServiceProvider\
	UNIX_PrecedenceServiceProvider\
	UNIX_PrintServiceProvider\
	UNIX_TimeServiceProvider\
	UNIX_SoftwareInstallationServiceProvider\
	UNIX_VLANServiceProvider\
	UNIX_Specific802dot1QVLANServiceProvider\
	UNIX_PowerUtilizationManagementServiceProvider\
	UNIX_ClusteringServiceProvider\
	UNIX_SharedDeviceManagementServiceProvider\
	UNIX_BatchServiceProvider\
	UNIX_iSCSIConfigurationServiceProvider\
	UNIX_OOBAlertServiceProvider\
	UNIX_StorageConfigurationServiceProvider\
	UNIX_IPConfigurationServiceProvider\
	UNIX_VirtualSystemMigrationServiceProvider\
	UNIX_MPLSCrossConnectProvider\
	UNIX_PlatformWatchdogServiceProvider\
	UNIX_FCHBADiagnosticTestProvider\
	UNIX_RAIDDiagnosticTestProvider\
	UNIX_CPUDiagnosticTestProvider\
	UNIX_EthernetNICDiagnosticTestProvider\
	UNIX_OpticalDriveDiagnosticTestProvider\
	UNIX_OpticalDriveDiagnosticSettingDataProvider\
	UNIX_DiskDriveDiagnosticTestProvider\
	UNIX_IBSubnetManagerProvider\
	UNIX_ObjectManagerProvider\
	UNIX_ObjectManagerAdapterProvider\
	UNIX_ProviderObjectManagerAdapterProvider\
	UNIX_ProtocolAdapterProvider\
	UNIX_FileSystemStatisticsServiceProvider\
	UNIX_BlockStatisticsServiceProvider\
	UNIX_USBRedirectionServiceProvider\
	UNIX_TextRedirectionServiceProvider\
	UNIX_BGPServiceProvider\
	UNIX_OSPFServiceProvider\
	UNIX_NATServiceProvider\
	UNIX_TransparentBridgingServiceProvider\
	UNIX_SourceRoutingServiceProvider\
	UNIX_SpanningTreeServiceProvider\
	UNIX_SwitchServiceProvider\
	UNIX_FileExportServiceProvider\
	UNIX_OperatingSystemProvider\
	UNIX_SWRFileProvider\
	UNIX_SWRPEPProvider\
	UNIX_SWRDatabaseProvider\
	UNIX_ProviderLibraryProvider\
	UNIX_ClusteringSAPProvider\
	UNIX_CredentialManagementSAPProvider\
	UNIX_USBRedirectionSAPProvider\
	UNIX_IPNetworkConnectionProvider\
	UNIX_PolicyTransferServiceAccessPointProvider\
	UNIX_LaunchInContextSAPProvider\
	UNIX_RemotePortProvider\
	UNIX_MPLSTunnelHopProvider\
	UNIX_SoftwareIdentityResourceProvider\
	UNIX_KVMRedirectionSAPProvider\
	UNIX_DHCPProtocolEndpointProvider\
	UNIX_SSHProtocolEndpointProvider\
	UNIX_SCSIProtocolEndpointProvider\
	UNIX_iSCSIProtocolEndpointProvider\
	UNIX_CLPProtocolEndpointProvider\
	UNIX_IPXProtocolEndpointProvider\
	UNIX_IPsecSAEndpointProvider\
	UNIX_IKESAEndpointProvider\
	UNIX_LANEndpointProvider\
	UNIX_WiFiEndpointProvider\
	UNIX_MPLSProtocolEndpointProvider\
	UNIX_WirelessLANEndpointProvider\
	UNIX_UDPProtocolEndpointProvider\
	UNIX_TCPProtocolEndpointProvider\
	UNIX_OSPFVirtualInterfaceProvider\
	UNIX_OSPFProtocolEndpointProvider\
	UNIX_VLANEndpointProvider\
	UNIX_LinkAggregator8023adProvider\
	UNIX_ATAProtocolEndpointProvider\
	UNIX_IPEncapsulationInterfaceProvider\
	UNIX_IPSubinterfaceProvider\
	UNIX_SwitchVirtualInterfaceProvider\
	UNIX_IPLoopbackProvider\
	UNIX_BGPProtocolEndpointProvider\
	UNIX_SwitchPortProvider\
	UNIX_DNSProtocolEndpointProvider\
	UNIX_LAGPort8023adProvider\
	UNIX_BatchSAPProvider\
	UNIX_TextRedirectionSAPProvider\
	UNIX_MediaRedirectionSAPProvider\
	UNIX_PrintSAPProvider\
	UNIX_ServiceAccessURIProvider\
	UNIX_ObjectManagerCommunicationMechanismProvider\
	UNIX_CIMXMLCommunicationMechanismProvider\
	UNIX_VLANProvider\
	UNIX_BootSAPProvider\
	UNIX_ProcessProvider\
	UNIX_ProcessorCoreProvider\
	UNIX_iSCSISessionProvider\
	UNIX_iSCSIConnectionProvider\
	UNIX_HardwareThreadProvider\
	UNIX_FileSystemProvider\
	UNIX_DatabaseStorageAreaProvider\
	UNIX_LocalFileSystemProvider\
	UNIX_RemoteFileSystemProvider\
	UNIX_NFSProvider\
	UNIX_ThreadProvider\
	UNIX_AccountProvider\
	UNIX_StoragePoolProvider

EXTRA_LIBRARIES = \
	-lpegprovider \
	-lpegclient \
	-lpegcommon \
	-lpegquerycommon \
	-lpegqueryexpression \
	-lpegcql \
	-lpegwql \
	-lpthread \
	-lutil \
	-lkvm

include $(ROOT)/mak/dynamic-library.mak





