#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////
#//
#//%/////////////////////////////////////////////////////////////////////////


ROOT = ../../../..
DIRS = \
	$(ROOT)/src/Providers/UNIXProviders/RedundancySetCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/JobCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/DiagnosticServiceJobCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/BlockStatisticsCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemStatisticsCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemSnapshotServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/USBRedirectionCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/MediaRedirectionCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerUtilizationManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiEndpointCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/WSManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/CIMXMLCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/SSHCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/CLPCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/RecordLogCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/LaunchInContextCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/AccountManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerTopologyCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/AccountCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiPortCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FCPortCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/OpaqueManagementDataCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/OperatingSystemCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPolicyServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/LoadBalancerServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FCSwitchCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/WBEMServerCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicatorLEDCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/CredentialManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/CertificateManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/BootServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ProcessorCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/TPMCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/AlarmDeviceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/DHCPCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/MetricServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FingerprintMatchingServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PlatformWatchdogServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ImportedFileShareCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PhysicalAssetCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/DeviceSharingCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/AllocationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/OSPFServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ZoneCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageNameBindingCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANSystemCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicationServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/BIOSServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ViewCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileImportCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ExportedFileShareCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VTLStatisticalDataServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/QueryCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/LocalizationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PrivilegeManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/RoleBasedManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/SoftwareInstallationServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIMultipathConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemReplicationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/RAIDDiagnosticServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetNICDiagnosticServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/CPUDiagnosticServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDriveDiagnosticServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FCHBADiagnosticServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/OpticalDriveDiagnosticServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ComputerSystemNodeCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/CommonDatabaseCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/RelationalDatabaseCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemReplicationServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolControllerMaskingCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/GroupMaskingMappingCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/IEEE8021xCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ReplicationServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/LAGControlCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ResourcePoolConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerManagementCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemSnapshotCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSICapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ImplementationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageLibraryCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANEndpointCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/ProviderCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageServerAsymmetryCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskPartitionConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageReplicationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/TierServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/TierPolicyServiceCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageTierCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/SpareConfigurationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FileExportCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemMigrationCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageElementCompositionCapabilities \
\
	$(ROOT)/src/Providers/UNIXProviders/FirewallRuleSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/LoadBalancingRuleSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/QoSPolicyRuleSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANEndpointSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/CLPSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageClientSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/CPUDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/RAIDDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDriveDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/FCHBADiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetNICDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/SAEndpointRefreshSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiEndpointSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/LogicalPortSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPortSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/FCPortSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/ReplicationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/AccessControlServiceSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/TimeZoneSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualEthernetSwitchSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/FCIPSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicationServiceSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/BootSourceSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/CommonDatabaseSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/BootSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/ExportedFileShareSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintServiceSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/StatisticalSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/CIFSSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/IPVersionSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/IPSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/ProcessorAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetPortAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/TCPSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/JobSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DHCPSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/StaticIPAssignmentSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/ExtendedStaticIPAssignmentSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DNSGeneralSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DNSSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/FCSwitchSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/ConfigurationData \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiNetworkDetectionSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemMigrationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIMultipathSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/NATStaticSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/NATListBasedSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseSegmentSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/AHTransform \
\
	$(ROOT)/src/Providers/UNIXProviders/ESPTransform \
\
	$(ROOT)/src/Providers/UNIXProviders/IPCOMPTransform \
\
	$(ROOT)/src/Providers/UNIXProviders/IPsecProposal \
\
	$(ROOT)/src/Providers/UNIXProviders/IKEProposal \
\
	$(ROOT)/src/Providers/UNIXProviders/TimeoutsForNATTranslation \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseParameter \
\
	$(ROOT)/src/Providers/UNIXProviders/BootConfigSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSISessionSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/SWRLimitSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSQosPRTrfcProf \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSCRLSPTrfcProf \
\
	$(ROOT)/src/Providers/UNIXProviders/SSHSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/OSStorageNameBinding \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageBridgeNameBinding \
\
	$(ROOT)/src/Providers/UNIXProviders/SynchronizationAspect \
\
	$(ROOT)/src/Providers/UNIXProviders/AccountSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/LAGPortPartnerSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/AdvancedStorageSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageSettingWithHints \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPolicyActionSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/LoadBalancingActionSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VideoHeadResolution \
\
	$(ROOT)/src/Providers/UNIXProviders/ImportedFileShareSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIConnectionSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/TierSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/TierPolicySettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/IEEE8021xSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/ZoneMembershipSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/GARPMembershipSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANMembershipSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/EnabledLogicalElementSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANSystemSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/RedundancySetSettingData \




DIR = Providers/UNIXProviders/SettingsDefineCapabilities
include $(ROOT)/mak/config.mak
LIBRARY = UNIX_SettingsDefineCapabilitiesProvider
EXTRA_INCLUDES += -I/usr/local/include -I./..

DEFINES +=  -DPROVIDER_LIB_NS="UNIX_SettingsDefineCapabilitiesLib" -DPROVIDER_LIB_NS_BEGIN="namespace UNIX_SettingsDefineCapabilitiesLib {"

SOURCES = \
	../CIMHelper.cpp \
	UNIX_SettingsDefineCapabilities.cpp \
	UNIX_SettingsDefineCapabilitiesProvider.cpp \
	UNIX_SettingsDefineCapabilitiesMain.cpp

ifeq ($(OS), aix)
	SOURCES += UNIX_SettingsDefineCapabilities_AIX.cpp
endif
ifeq ($(OS), darwin)
	SOURCES += UNIX_SettingsDefineCapabilities_DARWIN.cpp
endif
ifeq ($(OS), freebsd)
	SOURCES += UNIX_SettingsDefineCapabilities_FREEBSD.cpp
endif
ifeq ($(OS), hpux)
	SOURCES += UNIX_SettingsDefineCapabilities_HPUX.cpp
endif
ifeq ($(OS), linux)
	SOURCES += UNIX_SettingsDefineCapabilities_LINUX.cpp
endif
ifeq ($(OS), solaris)
	SOURCES += UNIX_SettingsDefineCapabilities_SOLARIS.cpp
endif
ifeq ($(OS), tru64)
	SOURCES += UNIX_SettingsDefineCapabilities_TRU64.cpp
endif
ifeq ($(OS), vms)
	SOURCES += UNIX_SettingsDefineCapabilities_VMS.cpp
endif
ifeq ($(OS), win32)
	SOURCES += UNIX_SettingsDefineCapabilities_WIN32.cpp
endif
ifeq ($(OS), zos)
	SOURCES += UNIX_SettingsDefineCapabilities_ZOS.cpp
endif
ifeq (, $(filter aix,darwin,freebsd,hpux,linux,solaris,tru64,vms,win32,zos $(OS)))

else
	SOURCES += UNIX_SettingsDefineCapabilities_STUB.cpp
endif

LIBRARIES += \
	UNIX_RedundancySetCapabilitiesProvider\
	UNIX_JobCapabilitiesProvider\
	UNIX_DiagnosticServiceJobCapabilitiesProvider\
	UNIX_BlockStatisticsCapabilitiesProvider\
	UNIX_FileSystemStatisticsCapabilitiesProvider\
	UNIX_VirtualSystemSnapshotServiceCapabilitiesProvider\
	UNIX_USBRedirectionCapabilitiesProvider\
	UNIX_MediaRedirectionCapabilitiesProvider\
	UNIX_PowerUtilizationManagementCapabilitiesProvider\
	UNIX_VirtualSystemManagementCapabilitiesProvider\
	UNIX_WiFiEndpointCapabilitiesProvider\
	UNIX_WSManagementCapabilitiesProvider\
	UNIX_CIMXMLCapabilitiesProvider\
	UNIX_SSHCapabilitiesProvider\
	UNIX_CLPCapabilitiesProvider\
	UNIX_RecordLogCapabilitiesProvider\
	UNIX_LaunchInContextCapabilitiesProvider\
	UNIX_AccountManagementCapabilitiesProvider\
	UNIX_PowerTopologyCapabilitiesProvider\
	UNIX_AccountCapabilitiesProvider\
	UNIX_WiFiPortCapabilitiesProvider\
	UNIX_FCPortCapabilitiesProvider\
	UNIX_OpaqueManagementDataCapabilitiesProvider\
	UNIX_OperatingSystemCapabilitiesProvider\
	UNIX_NetworkPolicyServiceCapabilitiesProvider\
	UNIX_LoadBalancerServiceCapabilitiesProvider\
	UNIX_FCSwitchCapabilitiesProvider\
	UNIX_WBEMServerCapabilitiesProvider\
	UNIX_IndicatorLEDCapabilitiesProvider\
	UNIX_CredentialManagementCapabilitiesProvider\
	UNIX_CertificateManagementCapabilitiesProvider\
	UNIX_BootServiceCapabilitiesProvider\
	UNIX_ProcessorCapabilitiesProvider\
	UNIX_TPMCapabilitiesProvider\
	UNIX_AlarmDeviceCapabilitiesProvider\
	UNIX_DHCPCapabilitiesProvider\
	UNIX_MetricServiceCapabilitiesProvider\
	UNIX_FingerprintMatchingServiceCapabilitiesProvider\
	UNIX_PlatformWatchdogServiceCapabilitiesProvider\
	UNIX_ImportedFileShareCapabilitiesProvider\
	UNIX_PhysicalAssetCapabilitiesProvider\
	UNIX_DeviceSharingCapabilitiesProvider\
	UNIX_AllocationCapabilitiesProvider\
	UNIX_PrintServiceCapabilitiesProvider\
	UNIX_OSPFServiceCapabilitiesProvider\
	UNIX_ZoneCapabilitiesProvider\
	UNIX_StorageNameBindingCapabilitiesProvider\
	UNIX_VLANSystemCapabilitiesProvider\
	UNIX_IndicationServiceCapabilitiesProvider\
	UNIX_BIOSServiceCapabilitiesProvider\
	UNIX_ViewCapabilitiesProvider\
	UNIX_FileImportCapabilitiesProvider\
	UNIX_ExportedFileShareCapabilitiesProvider\
	UNIX_VTLStatisticalDataServiceCapabilitiesProvider\
	UNIX_QueryCapabilitiesProvider\
	UNIX_LocalizationCapabilitiesProvider\
	UNIX_PrivilegeManagementCapabilitiesProvider\
	UNIX_RoleBasedManagementCapabilitiesProvider\
	UNIX_SoftwareInstallationServiceCapabilitiesProvider\
	UNIX_SCSIMultipathConfigurationCapabilitiesProvider\
	UNIX_FileSystemReplicationCapabilitiesProvider\
	UNIX_RAIDDiagnosticServiceCapabilitiesProvider\
	UNIX_EthernetNICDiagnosticServiceCapabilitiesProvider\
	UNIX_CPUDiagnosticServiceCapabilitiesProvider\
	UNIX_DiskDriveDiagnosticServiceCapabilitiesProvider\
	UNIX_FCHBADiagnosticServiceCapabilitiesProvider\
	UNIX_OpticalDriveDiagnosticServiceCapabilitiesProvider\
	UNIX_iSCSIConfigurationCapabilitiesProvider\
	UNIX_ComputerSystemNodeCapabilitiesProvider\
	UNIX_MPLSCapabilitiesProvider\
	UNIX_CommonDatabaseCapabilitiesProvider\
	UNIX_RelationalDatabaseCapabilitiesProvider\
	UNIX_FileSystemConfigurationCapabilitiesProvider\
	UNIX_FileSystemReplicationServiceCapabilitiesProvider\
	UNIX_ProtocolControllerMaskingCapabilitiesProvider\
	UNIX_GroupMaskingMappingCapabilitiesProvider\
	UNIX_FileSystemCapabilitiesProvider\
	UNIX_IEEE8021xCapabilitiesProvider\
	UNIX_ReplicationServiceCapabilitiesProvider\
	UNIX_LAGControlCapabilitiesProvider\
	UNIX_ResourcePoolConfigurationCapabilitiesProvider\
	UNIX_PowerManagementCapabilitiesProvider\
	UNIX_VirtualSystemSnapshotCapabilitiesProvider\
	UNIX_iSCSICapabilitiesProvider\
	UNIX_ImplementationCapabilitiesProvider\
	UNIX_StorageLibraryCapabilitiesProvider\
	UNIX_VLANEndpointCapabilitiesProvider\
	UNIX_ProviderCapabilitiesProvider\
	UNIX_StorageServerAsymmetryCapabilitiesProvider\
	UNIX_DiskPartitionConfigurationCapabilitiesProvider\
	UNIX_StorageReplicationCapabilitiesProvider\
	UNIX_StorageConfigurationCapabilitiesProvider\
	UNIX_TierServiceCapabilitiesProvider\
	UNIX_TierPolicyServiceCapabilitiesProvider\
	UNIX_StorageCapabilitiesProvider\
	UNIX_StorageTierCapabilitiesProvider\
	UNIX_SpareConfigurationCapabilitiesProvider\
	UNIX_FileExportCapabilitiesProvider\
	UNIX_VirtualSystemMigrationCapabilitiesProvider\
	UNIX_StorageElementCompositionCapabilitiesProvider\
	UNIX_FirewallRuleSettingDataProvider\
	UNIX_LoadBalancingRuleSettingDataProvider\
	UNIX_QoSPolicyRuleSettingDataProvider\
	UNIX_VLANEndpointSettingDataProvider\
	UNIX_CLPSettingDataProvider\
	UNIX_StorageClientSettingDataProvider\
	UNIX_CPUDiagnosticSettingDataProvider\
	UNIX_RAIDDiagnosticSettingDataProvider\
	UNIX_DiskDriveDiagnosticSettingDataProvider\
	UNIX_FCHBADiagnosticSettingDataProvider\
	UNIX_EthernetNICDiagnosticSettingDataProvider\
	UNIX_SAEndpointRefreshSettingsProvider\
	UNIX_WiFiEndpointSettingsProvider\
	UNIX_LogicalPortSettingsProvider\
	UNIX_NetworkPortSettingsProvider\
	UNIX_FCPortSettingsProvider\
	UNIX_ReplicationSettingDataProvider\
	UNIX_AccessControlServiceSettingDataProvider\
	UNIX_TimeZoneSettingDataProvider\
	UNIX_VirtualSystemSettingDataProvider\
	UNIX_VirtualEthernetSwitchSettingDataProvider\
	UNIX_FCIPSettingsProvider\
	UNIX_IndicationServiceSettingDataProvider\
	UNIX_BootSourceSettingProvider\
	UNIX_CommonDatabaseSettingDataProvider\
	UNIX_BootSettingDataProvider\
	UNIX_ExportedFileShareSettingProvider\
	UNIX_PrintServiceSettingsProvider\
	UNIX_StatisticalSettingProvider\
	UNIX_CIFSSettingDataProvider\
	UNIX_IPVersionSettingDataProvider\
	UNIX_IPSettingsProvider\
	UNIX_StorageAllocationSettingDataProvider\
	UNIX_ProcessorAllocationSettingDataProvider\
	UNIX_EthernetPortAllocationSettingDataProvider\
	UNIX_PowerAllocationSettingDataProvider\
	UNIX_TCPSettingsProvider\
	UNIX_FileSystemSettingProvider\
	UNIX_JobSettingDataProvider\
	UNIX_DHCPSettingDataProvider\
	UNIX_StaticIPAssignmentSettingDataProvider\
	UNIX_ExtendedStaticIPAssignmentSettingDataProvider\
	UNIX_DNSGeneralSettingDataProvider\
	UNIX_DNSSettingDataProvider\
	UNIX_FCSwitchSettingsProvider\
	UNIX_ConfigurationDataProvider\
	UNIX_WiFiNetworkDetectionSettingsProvider\
	UNIX_VirtualSystemMigrationSettingDataProvider\
	UNIX_SCSIMultipathSettingsProvider\
	UNIX_NATStaticSettingsProvider\
	UNIX_NATListBasedSettingsProvider\
	UNIX_FileSystemSettingDataProvider\
	UNIX_DatabaseSegmentSettingDataProvider\
	UNIX_AHTransformProvider\
	UNIX_ESPTransformProvider\
	UNIX_IPCOMPTransformProvider\
	UNIX_IPsecProposalProvider\
	UNIX_IKEProposalProvider\
	UNIX_TimeoutsForNATTranslationProvider\
	UNIX_DatabaseParameterProvider\
	UNIX_BootConfigSettingProvider\
	UNIX_iSCSISessionSettingsProvider\
	UNIX_SWRLimitSettingProvider\
	UNIX_MPLSQosPRTrfcProfProvider\
	UNIX_MPLSCRLSPTrfcProfProvider\
	UNIX_SSHSettingDataProvider\
	UNIX_OSStorageNameBindingProvider\
	UNIX_StorageBridgeNameBindingProvider\
	UNIX_SynchronizationAspectProvider\
	UNIX_AccountSettingDataProvider\
	UNIX_LAGPortPartnerSettingsProvider\
	UNIX_StorageSettingProvider\
	UNIX_AdvancedStorageSettingProvider\
	UNIX_StorageSettingWithHintsProvider\
	UNIX_NetworkPolicyActionSettingDataProvider\
	UNIX_LoadBalancingActionSettingDataProvider\
	UNIX_VideoHeadResolutionProvider\
	UNIX_ImportedFileShareSettingProvider\
	UNIX_iSCSIConnectionSettingsProvider\
	UNIX_TierSettingDataProvider\
	UNIX_TierPolicySettingDataProvider\
	UNIX_IEEE8021xSettingsProvider\
	UNIX_ZoneMembershipSettingDataProvider\
	UNIX_GARPMembershipSettingDataProvider\
	UNIX_VLANMembershipSettingDataProvider\
	UNIX_EnabledLogicalElementSettingDataProvider\
	UNIX_VLANSystemSettingDataProvider\
	UNIX_RedundancySetSettingDataProvider

EXTRA_LIBRARIES = \
	-lpegprovider \
	-lpegclient \
	-lpegcommon \
	-lpegquerycommon \
	-lpegqueryexpression \
	-lpegcql \
	-lpegwql \
	-lpthread \
	-lutil \
	-lkvm

include $(ROOT)/mak/dynamic-library.mak





