#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////
#//
#//%/////////////////////////////////////////////////////////////////////////


ROOT = ../../../..
DIRS = \
	$(ROOT)/src/Providers/UNIXProviders/FirewallRuleSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/LoadBalancingRuleSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/QoSPolicyRuleSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANEndpointSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/CLPSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageClientSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/CPUDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/RAIDDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDriveDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/FCHBADiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetNICDiagnosticSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/SAEndpointRefreshSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiEndpointSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/LogicalPortSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPortSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/FCPortSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/ReplicationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/AccessControlServiceSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/TimeZoneSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualEthernetSwitchSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/FCIPSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicationServiceSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/BootSourceSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/CommonDatabaseSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/BootSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/ExportedFileShareSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/PrintServiceSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/StatisticalSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/CIFSSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/IPVersionSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/IPSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/ProcessorAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetPortAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerAllocationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/TCPSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/JobSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DHCPSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/StaticIPAssignmentSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/ExtendedStaticIPAssignmentSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DNSGeneralSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DNSSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/FCSwitchSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/ConfigurationData \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiNetworkDetectionSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/VirtualSystemMigrationSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIMultipathSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/NATStaticSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/NATListBasedSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/FileSystemSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseSegmentSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/AHTransform \
\
	$(ROOT)/src/Providers/UNIXProviders/ESPTransform \
\
	$(ROOT)/src/Providers/UNIXProviders/IPCOMPTransform \
\
	$(ROOT)/src/Providers/UNIXProviders/IPsecProposal \
\
	$(ROOT)/src/Providers/UNIXProviders/IKEProposal \
\
	$(ROOT)/src/Providers/UNIXProviders/TimeoutsForNATTranslation \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseParameter \
\
	$(ROOT)/src/Providers/UNIXProviders/BootConfigSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSISessionSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/SWRLimitSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSQosPRTrfcProf \
\
	$(ROOT)/src/Providers/UNIXProviders/MPLSCRLSPTrfcProf \
\
	$(ROOT)/src/Providers/UNIXProviders/SSHSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/OSStorageNameBinding \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageBridgeNameBinding \
\
	$(ROOT)/src/Providers/UNIXProviders/SynchronizationAspect \
\
	$(ROOT)/src/Providers/UNIXProviders/AccountSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/LAGPortPartnerSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/AdvancedStorageSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/StorageSettingWithHints \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPolicyActionSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/LoadBalancingActionSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VideoHeadResolution \
\
	$(ROOT)/src/Providers/UNIXProviders/ImportedFileShareSetting \
\
	$(ROOT)/src/Providers/UNIXProviders/iSCSIConnectionSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/TierSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/TierPolicySettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/IEEE8021xSettings \
\
	$(ROOT)/src/Providers/UNIXProviders/ZoneMembershipSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/GARPMembershipSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANMembershipSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/EnabledLogicalElementSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/VLANSystemSettingData \
\
	$(ROOT)/src/Providers/UNIXProviders/RedundancySetSettingData \




DIR = Providers/UNIXProviders/SettingsAffectSettings
include $(ROOT)/mak/config.mak
LIBRARY = UNIX_SettingsAffectSettingsProvider
EXTRA_INCLUDES += -I/usr/local/include -I./..

DEFINES +=  -DPROVIDER_LIB_NS="UNIX_SettingsAffectSettingsLib" -DPROVIDER_LIB_NS_BEGIN="namespace UNIX_SettingsAffectSettingsLib {"

SOURCES = \
	../CIMHelper.cpp \
	UNIX_SettingsAffectSettings.cpp \
	UNIX_SettingsAffectSettingsProvider.cpp \
	UNIX_SettingsAffectSettingsMain.cpp

ifeq ($(OS), aix)
	SOURCES += UNIX_SettingsAffectSettings_AIX.cpp
endif
ifeq ($(OS), darwin)
	SOURCES += UNIX_SettingsAffectSettings_DARWIN.cpp
endif
ifeq ($(OS), freebsd)
	SOURCES += UNIX_SettingsAffectSettings_FREEBSD.cpp
endif
ifeq ($(OS), hpux)
	SOURCES += UNIX_SettingsAffectSettings_HPUX.cpp
endif
ifeq ($(OS), linux)
	SOURCES += UNIX_SettingsAffectSettings_LINUX.cpp
endif
ifeq ($(OS), solaris)
	SOURCES += UNIX_SettingsAffectSettings_SOLARIS.cpp
endif
ifeq ($(OS), tru64)
	SOURCES += UNIX_SettingsAffectSettings_TRU64.cpp
endif
ifeq ($(OS), vms)
	SOURCES += UNIX_SettingsAffectSettings_VMS.cpp
endif
ifeq ($(OS), win32)
	SOURCES += UNIX_SettingsAffectSettings_WIN32.cpp
endif
ifeq ($(OS), zos)
	SOURCES += UNIX_SettingsAffectSettings_ZOS.cpp
endif
ifeq (, $(filter aix,darwin,freebsd,hpux,linux,solaris,tru64,vms,win32,zos $(OS)))

else
	SOURCES += UNIX_SettingsAffectSettings_STUB.cpp
endif

LIBRARIES += \
	UNIX_FirewallRuleSettingDataProvider\
	UNIX_LoadBalancingRuleSettingDataProvider\
	UNIX_QoSPolicyRuleSettingDataProvider\
	UNIX_VLANEndpointSettingDataProvider\
	UNIX_CLPSettingDataProvider\
	UNIX_StorageClientSettingDataProvider\
	UNIX_CPUDiagnosticSettingDataProvider\
	UNIX_RAIDDiagnosticSettingDataProvider\
	UNIX_DiskDriveDiagnosticSettingDataProvider\
	UNIX_FCHBADiagnosticSettingDataProvider\
	UNIX_EthernetNICDiagnosticSettingDataProvider\
	UNIX_SAEndpointRefreshSettingsProvider\
	UNIX_WiFiEndpointSettingsProvider\
	UNIX_LogicalPortSettingsProvider\
	UNIX_NetworkPortSettingsProvider\
	UNIX_FCPortSettingsProvider\
	UNIX_ReplicationSettingDataProvider\
	UNIX_AccessControlServiceSettingDataProvider\
	UNIX_TimeZoneSettingDataProvider\
	UNIX_VirtualSystemSettingDataProvider\
	UNIX_VirtualEthernetSwitchSettingDataProvider\
	UNIX_FCIPSettingsProvider\
	UNIX_IndicationServiceSettingDataProvider\
	UNIX_BootSourceSettingProvider\
	UNIX_CommonDatabaseSettingDataProvider\
	UNIX_BootSettingDataProvider\
	UNIX_ExportedFileShareSettingProvider\
	UNIX_PrintServiceSettingsProvider\
	UNIX_StatisticalSettingProvider\
	UNIX_CIFSSettingDataProvider\
	UNIX_IPVersionSettingDataProvider\
	UNIX_IPSettingsProvider\
	UNIX_StorageAllocationSettingDataProvider\
	UNIX_ProcessorAllocationSettingDataProvider\
	UNIX_EthernetPortAllocationSettingDataProvider\
	UNIX_PowerAllocationSettingDataProvider\
	UNIX_TCPSettingsProvider\
	UNIX_FileSystemSettingProvider\
	UNIX_JobSettingDataProvider\
	UNIX_DHCPSettingDataProvider\
	UNIX_StaticIPAssignmentSettingDataProvider\
	UNIX_ExtendedStaticIPAssignmentSettingDataProvider\
	UNIX_DNSGeneralSettingDataProvider\
	UNIX_DNSSettingDataProvider\
	UNIX_FCSwitchSettingsProvider\
	UNIX_ConfigurationDataProvider\
	UNIX_WiFiNetworkDetectionSettingsProvider\
	UNIX_VirtualSystemMigrationSettingDataProvider\
	UNIX_SCSIMultipathSettingsProvider\
	UNIX_NATStaticSettingsProvider\
	UNIX_NATListBasedSettingsProvider\
	UNIX_FileSystemSettingDataProvider\
	UNIX_DatabaseSegmentSettingDataProvider\
	UNIX_AHTransformProvider\
	UNIX_ESPTransformProvider\
	UNIX_IPCOMPTransformProvider\
	UNIX_IPsecProposalProvider\
	UNIX_IKEProposalProvider\
	UNIX_TimeoutsForNATTranslationProvider\
	UNIX_DatabaseParameterProvider\
	UNIX_BootConfigSettingProvider\
	UNIX_iSCSISessionSettingsProvider\
	UNIX_SWRLimitSettingProvider\
	UNIX_MPLSQosPRTrfcProfProvider\
	UNIX_MPLSCRLSPTrfcProfProvider\
	UNIX_SSHSettingDataProvider\
	UNIX_OSStorageNameBindingProvider\
	UNIX_StorageBridgeNameBindingProvider\
	UNIX_SynchronizationAspectProvider\
	UNIX_AccountSettingDataProvider\
	UNIX_LAGPortPartnerSettingsProvider\
	UNIX_StorageSettingProvider\
	UNIX_AdvancedStorageSettingProvider\
	UNIX_StorageSettingWithHintsProvider\
	UNIX_NetworkPolicyActionSettingDataProvider\
	UNIX_LoadBalancingActionSettingDataProvider\
	UNIX_VideoHeadResolutionProvider\
	UNIX_ImportedFileShareSettingProvider\
	UNIX_iSCSIConnectionSettingsProvider\
	UNIX_TierSettingDataProvider\
	UNIX_TierPolicySettingDataProvider\
	UNIX_IEEE8021xSettingsProvider\
	UNIX_ZoneMembershipSettingDataProvider\
	UNIX_GARPMembershipSettingDataProvider\
	UNIX_VLANMembershipSettingDataProvider\
	UNIX_EnabledLogicalElementSettingDataProvider\
	UNIX_VLANSystemSettingDataProvider\
	UNIX_RedundancySetSettingDataProvider

EXTRA_LIBRARIES = \
	-lpegprovider \
	-lpegclient \
	-lpegcommon \
	-lpegquerycommon \
	-lpegqueryexpression \
	-lpegcql \
	-lpegwql \
	-lpthread \
	-lutil \
	-lkvm

include $(ROOT)/mak/dynamic-library.mak





