//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////

#pragma include ("Meta_Class20R.mof")
#pragma include ("CIM_ManagedElement20R.mof")
#pragma include ("UNIX_SoftwareIDTag1977020R.mof")
#pragma include ("CIM_SettingData20R.mof")
#pragma include ("CIM_NetworkPolicyRuleSettingData20R.mof")
#pragma include ("UNIX_FirewallRuleSettingData20R.mof")
#pragma include ("UNIX_LoadBalancingRuleSettingData20R.mof")
#pragma include ("UNIX_QoSPolicyRuleSettingData20R.mof")
#pragma include ("UNIX_VLANEndpointSettingData20R.mof")
#pragma include ("UNIX_CLPSettingData20R.mof")
#pragma include ("UNIX_StorageClientSettingData20R.mof")
#pragma include ("CIM_DiagnosticSettingData20R.mof")
#pragma include ("UNIX_CPUDiagnosticSettingData20R.mof")
#pragma include ("UNIX_RAIDDiagnosticSettingData20R.mof")
#pragma include ("UNIX_DiskDriveDiagnosticSettingData20R.mof")
#pragma include ("UNIX_FCHBADiagnosticSettingData20R.mof")
#pragma include ("UNIX_EthernetNICDiagnosticSettingData20R.mof")
#pragma include ("UNIX_SAEndpointRefreshSettings20R.mof")
#pragma include ("UNIX_WiFiEndpointSettings20R.mof")
#pragma include ("UNIX_LogicalPortSettings20R.mof")
#pragma include ("UNIX_NetworkPortSettings20R.mof")
#pragma include ("UNIX_FCPortSettings20R.mof")
#pragma include ("UNIX_ReplicationSettingData20R.mof")
#pragma include ("UNIX_AccessControlServiceSettingData20R.mof")
#pragma include ("UNIX_TimeZoneSettingData20R.mof")
#pragma include ("UNIX_VirtualSystemSettingData20R.mof")
#pragma include ("UNIX_VirtualEthernetSwitchSettingData20R.mof")
#pragma include ("UNIX_FCIPSettings20R.mof")
#pragma include ("UNIX_IndicationServiceSettingData20R.mof")
#pragma include ("UNIX_BootSourceSetting20R.mof")
#pragma include ("UNIX_CommonDatabaseSettingData20R.mof")
#pragma include ("UNIX_BootSettingData20R.mof")
#pragma include ("UNIX_ExportedFileShareSetting20R.mof")
#pragma include ("UNIX_PrintServiceSettings20R.mof")
#pragma include ("UNIX_StatisticalSetting20R.mof")
#pragma include ("UNIX_CIFSSettingData20R.mof")
#pragma include ("UNIX_IPVersionSettingData20R.mof")
#pragma include ("UNIX_IPSettings20R.mof")
#pragma include ("CIM_ResourceAllocationSettingData20R.mof")
#pragma include ("UNIX_StorageAllocationSettingData20R.mof")
#pragma include ("UNIX_ProcessorAllocationSettingData20R.mof")
#pragma include ("UNIX_EthernetPortAllocationSettingData20R.mof")
#pragma include ("UNIX_PowerAllocationSettingData20R.mof")
#pragma include ("UNIX_TCPSettings20R.mof")
#pragma include ("UNIX_FileSystemSetting20R.mof")
#pragma include ("UNIX_JobSettingData20R.mof")
#pragma include ("CIM_IPAssignmentSettingData20R.mof")
#pragma include ("UNIX_DHCPSettingData20R.mof")
#pragma include ("UNIX_StaticIPAssignmentSettingData20R.mof")
#pragma include ("UNIX_ExtendedStaticIPAssignmentSettingData20R.mof")
#pragma include ("UNIX_DNSGeneralSettingData20R.mof")
#pragma include ("UNIX_DNSSettingData20R.mof")
#pragma include ("UNIX_FCSwitchSettings20R.mof")
#pragma include ("UNIX_ConfigurationData20R.mof")
#pragma include ("UNIX_WiFiNetworkDetectionSettings20R.mof")
#pragma include ("UNIX_VirtualSystemMigrationSettingData20R.mof")
#pragma include ("UNIX_SCSIMultipathSettings20R.mof")
#pragma include ("CIM_ScopedSettingData20R.mof")
#pragma include ("CIM_NATSettingData20R.mof")
#pragma include ("UNIX_NATStaticSettings20R.mof")
#pragma include ("UNIX_NATListBasedSettings20R.mof")
#pragma include ("UNIX_FileSystemSettingData20R.mof")
#pragma include ("UNIX_DatabaseSegmentSettingData20R.mof")
#pragma include ("CIM_SATransform20R.mof")
#pragma include ("UNIX_AHTransform20R.mof")
#pragma include ("UNIX_ESPTransform20R.mof")
#pragma include ("UNIX_IPCOMPTransform20R.mof")
#pragma include ("CIM_SAProposal20R.mof")
#pragma include ("UNIX_IPsecProposal20R.mof")
#pragma include ("UNIX_IKEProposal20R.mof")
#pragma include ("UNIX_TimeoutsForNATTranslation20R.mof")
#pragma include ("UNIX_DatabaseParameter20R.mof")
#pragma include ("UNIX_BootConfigSetting20R.mof")
#pragma include ("UNIX_iSCSISessionSettings20R.mof")
#pragma include ("UNIX_SWRLimitSetting20R.mof")
#pragma include ("UNIX_MPLSQosPRTrfcProf20R.mof")
#pragma include ("UNIX_MPLSCRLSPTrfcProf20R.mof")
#pragma include ("UNIX_SSHSettingData20R.mof")
#pragma include ("CIM_StorageNameBinding20R.mof")
#pragma include ("UNIX_OSStorageNameBinding20R.mof")
#pragma include ("UNIX_StorageBridgeNameBinding20R.mof")
#pragma include ("UNIX_SynchronizationAspect20R.mof")
#pragma include ("UNIX_AccountSettingData20R.mof")
#pragma include ("UNIX_LAGPortPartnerSettings20R.mof")
#pragma include ("UNIX_StorageSetting20R.mof")
#pragma include ("UNIX_AdvancedStorageSetting20R.mof")
#pragma include ("UNIX_StorageSettingWithHints20R.mof")
#pragma include ("UNIX_NetworkPolicyActionSettingData20R.mof")
#pragma include ("UNIX_LoadBalancingActionSettingData20R.mof")
#pragma include ("UNIX_VideoHeadResolution20R.mof")
#pragma include ("UNIX_ImportedFileShareSetting20R.mof")
#pragma include ("UNIX_iSCSIConnectionSettings20R.mof")
#pragma include ("UNIX_TierSettingData20R.mof")
#pragma include ("UNIX_TierPolicySettingData20R.mof")
#pragma include ("UNIX_IEEE8021xSettings20R.mof")
#pragma include ("CIM_ConnectivityMembershipSettingData20R.mof")
#pragma include ("UNIX_ZoneMembershipSettingData20R.mof")
#pragma include ("UNIX_GARPMembershipSettingData20R.mof")
#pragma include ("UNIX_VLANMembershipSettingData20R.mof")
#pragma include ("UNIX_EnabledLogicalElementSettingData20R.mof")
#pragma include ("UNIX_VLANSystemSettingData20R.mof")
#pragma include ("UNIX_RedundancySetSettingData20R.mof")
#pragma include ("CIM_ListenerDestination20R.mof")
#pragma include ("UNIX_ListenerDestinationLog20R.mof")
#pragma include ("UNIX_ListenerDestinationWSManagement20R.mof")
#pragma include ("CIM_IndicationHandler20R.mof")
#pragma include ("UNIX_IndicationHandlerCIMXML20R.mof")
#pragma include ("UNIX_ListenerDestinationCIMXML20R.mof")
#pragma include ("CIM_StatisticalInformation20R.mof")
#pragma include ("CIM_DeviceStatisticalInformation20R.mof")
#pragma include ("UNIX_FibrePortEventCounters20R.mof")
#pragma include ("UNIX_FCAdapterEventCounters20R.mof")
#pragma include ("UNIX_LabelReaderStatInfo20R.mof")
#pragma include ("UNIX_MediaAccessStatInfo20R.mof")
#pragma include ("UNIX_SystemStatisticalInformation20R.mof")
#pragma include ("CIM_ServiceStatisticalInformation20R.mof")
#pragma include ("UNIX_BGPStatistics20R.mof")
#pragma include ("UNIX_TransparentBridgingStatistics20R.mof")
#pragma include ("UNIX_SpanningTreeStatistics20R.mof")
#pragma include ("UNIX_ProcessStatisticalInformation20R.mof")
#pragma include ("UNIX_PhysicalStatisticalInformation20R.mof")
#pragma include ("UNIX_MediaPhysicalStatInfo20R.mof")
#pragma include ("CIM_SAPStatisticalInformation20R.mof")
#pragma include ("UNIX_SwitchPortTransparentBridgingStatistics20R.mof")
#pragma include ("UNIX_SwitchPortStatistics20R.mof")
#pragma include ("UNIX_SwitchPortSpanningTreeStatistics20R.mof")
#pragma include ("UNIX_SwitchPortSourceRoutingStatistics20R.mof")
#pragma include ("UNIX_DeviceErrorCounts20R.mof")
#pragma include ("CIM_ManagedSystemElement20R.mof")
#pragma include ("CIM_PhysicalElement20R.mof")
#pragma include ("CIM_PhysicalComponent20R.mof")
#pragma include ("UNIX_PhysicalMedia20R.mof")
#pragma include ("UNIX_PhysicalTape20R.mof")
#pragma include ("UNIX_Chip20R.mof")
#pragma include ("UNIX_PhysicalMemory20R.mof")
#pragma include ("UNIX_PhysicalConnector20R.mof")
#pragma include ("UNIX_Slot20R.mof")
#pragma include ("UNIX_PhysicalLink20R.mof")
#pragma include ("CIM_PhysicalPackage20R.mof")
#pragma include ("UNIX_Card20R.mof")
#pragma include ("UNIX_SystemBusCard20R.mof")
#pragma include ("CIM_PhysicalFrame20R.mof")
#pragma include ("UNIX_Chassis20R.mof")
#pragma include ("UNIX_Rack20R.mof")
#pragma include ("UNIX_PackageLocation20R.mof")
#pragma include ("UNIX_StorageMediaLocation20R.mof")
#pragma include ("UNIX_Magazine20R.mof")
#pragma include ("UNIX_ComponentBay20R.mof")
#pragma include ("CIM_LogicalElement20R.mof")
#pragma include ("CIM_SqlObject20R.mof")
#pragma include ("UNIX_SqlSchema20R.mof")
#pragma include ("UNIX_SqlTable20R.mof")
#pragma include ("UNIX_SqlTrigger20R.mof")
#pragma include ("UNIX_SqlDomain20R.mof")
#pragma include ("UNIX_SqlDomainConstraint20R.mof")
#pragma include ("UNIX_SqlUserDefinedType20R.mof")
#pragma include ("CIM_FilterEntryBase20R.mof")
#pragma include ("UNIX_Hdr8021Filter20R.mof")
#pragma include ("UNIX_PreambleFilter20R.mof")
#pragma include ("UNIX_X509CredentialFilterEntry20R.mof")
#pragma include ("UNIX_PeerIDPayloadFilterEntry20R.mof")
#pragma include ("UNIX_FilterEntry20R.mof")
#pragma include ("UNIX_IPHeadersFilter20R.mof")
#pragma include ("UNIX_IPSOFilterEntry20R.mof")
#pragma include ("UNIX_AuthenticationRequirement20R.mof")
#pragma include ("UNIX_DynamicForwardingEntry20R.mof")
#pragma include ("UNIX_SqlCharacterSet20R.mof")
#pragma include ("CIM_MPLSSegment20R.mof")
#pragma include ("UNIX_MPLSInSegment20R.mof")
#pragma include ("UNIX_MPLSOutSegment20R.mof")
#pragma include ("UNIX_NextHopRouting20R.mof")
#pragma include ("UNIX_IPRoute20R.mof")
#pragma include ("UNIX_BGPIPRoute20R.mof")
#pragma include ("CIM_EnabledLogicalElement20R.mof")
#pragma include ("UNIX_MPLSLSP20R.mof")
#pragma include ("UNIX_CommonDatabase20R.mof")
#pragma include ("UNIX_MPLSTunnel20R.mof")
#pragma include ("UNIX_ReplicationEntity20R.mof")
#pragma include ("CIM_JobDestination20R.mof")
#pragma include ("UNIX_PrintQueue20R.mof")
#pragma include ("UNIX_JobQueue20R.mof")
#pragma include ("CIM_AllocatedLogicalElement20R.mof")
#pragma include ("CIM_System20R.mof")
#pragma include ("CIM_AdminDomain20R.mof")
#pragma include ("UNIX_ReusablePolicyContainer20R.mof")
#pragma include ("UNIX_PolicyRepository20R.mof")
#pragma include ("UNIX_AutonomousSystem20R.mof")
#pragma include ("UNIX_RoutingProtocolDomain20R.mof")
#pragma include ("UNIX_OSPFArea20R.mof")
#pragma include ("UNIX_Network20R.mof")
#pragma include ("UNIX_VLANNetwork20R.mof")
#pragma include ("UNIX_TierDomain20R.mof")
#pragma include ("UNIX_ApplicationSystem20R.mof")
#pragma include ("UNIX_DatabaseSystem20R.mof")
#pragma include ("UNIX_StorageLibrary20R.mof")
#pragma include ("CIM_ComputerSystem20R.mof")
#pragma include ("UNIX_VirtualComputerSystem20R.mof")
#pragma include ("UNIX_Cluster20R.mof")
#pragma include ("UNIX_ComputerSystem20R.mof")
#pragma include ("CIM_LogicalDevice20R.mof")
#pragma include ("UNIX_SCSIArbitraryLogicalUnit20R.mof")
#pragma include ("UNIX_Button20R.mof")
#pragma include ("CIM_PowerSource20R.mof")
#pragma include ("UNIX_PowerSupply20R.mof")
#pragma include ("UNIX_UninterruptiblePowerSupply20R.mof")
#pragma include ("UNIX_Battery20R.mof")
#pragma include ("CIM_MediaAccessDevice20R.mof")
#pragma include ("UNIX_TapeDrive20R.mof")
#pragma include ("UNIX_CDROMDrive20R.mof")
#pragma include ("UNIX_WORMDrive20R.mof")
#pragma include ("UNIX_DiskDrive20R.mof")
#pragma include ("UNIX_DVDDrive20R.mof")
#pragma include ("UNIX_DisketteDrive20R.mof")
#pragma include ("UNIX_MagnetoOpticalDrive20R.mof")
#pragma include ("UNIX_USBDevice20R.mof")
#pragma include ("UNIX_USBHub20R.mof")
#pragma include ("UNIX_PowerConnectionPoint20R.mof")
#pragma include ("UNIX_LabelReader20R.mof")
#pragma include ("CIM_StorageExtent20R.mof")
#pragma include ("UNIX_LogicalDisk20R.mof")
#pragma include ("UNIX_Snapshot20R.mof")
#pragma include ("CIM_MediaPartition20R.mof")
#pragma include ("CIM_GenericDiskPartition20R.mof")
#pragma include ("UNIX_VTOCDiskPartition20R.mof")
#pragma include ("UNIX_GPTDiskPartition20R.mof")
#pragma include ("UNIX_DiskPartition20R.mof")
#pragma include ("UNIX_TapePartition20R.mof")
#pragma include ("UNIX_CompositeExtent20R.mof")
#pragma include ("UNIX_ProtectedSpaceExtent20R.mof")
#pragma include ("UNIX_PhysicalExtent20R.mof")
#pragma include ("UNIX_DatabaseSegment20R.mof")
#pragma include ("UNIX_AggregatePExtent20R.mof")
#pragma include ("CIM_StorageVolume20R.mof")
#pragma include ("UNIX_VolumeSet20R.mof")
#pragma include ("UNIX_OpaqueManagementData20R.mof")
#pragma include ("UNIX_AggregatePSExtent20R.mof")
#pragma include ("CIM_Memory20R.mof")
#pragma include ("UNIX_CacheMemory20R.mof")
#pragma include ("UNIX_VolatileStorage20R.mof")
#pragma include ("UNIX_NonVolatileStorage20R.mof")
#pragma include ("UNIX_Printer20R.mof")
#pragma include ("CIM_Sensor20R.mof")
#pragma include ("CIM_NumericSensor20R.mof")
#pragma include ("UNIX_CurrentSensor20R.mof")
#pragma include ("UNIX_TemperatureSensor20R.mof")
#pragma include ("UNIX_VoltageSensor20R.mof")
#pragma include ("UNIX_Tachometer20R.mof")
#pragma include ("UNIX_MultiStateSensor20R.mof")
#pragma include ("UNIX_BinarySensor20R.mof")
#pragma include ("UNIX_DiscreteSensor20R.mof")
#pragma include ("CIM_Modem20R.mof")
#pragma include ("CIM_ConnectionBasedModem20R.mof")
#pragma include ("UNIX_CableModem20R.mof")
#pragma include ("CIM_DSLModem20R.mof")
#pragma include ("UNIX_ADSLModem20R.mof")
#pragma include ("UNIX_VDSLModem20R.mof")
#pragma include ("UNIX_HDSLModem20R.mof")
#pragma include ("UNIX_SDSLModem20R.mof")
#pragma include ("CIM_CallBasedModem20R.mof")
#pragma include ("CIM_POTSModem20R.mof")
#pragma include ("UNIX_Unimodem20R.mof")
#pragma include ("UNIX_ISDNModem20R.mof")
#pragma include ("CIM_UserDevice20R.mof")
#pragma include ("UNIX_Keyboard20R.mof")
#pragma include ("UNIX_PointingDevice20R.mof")
#pragma include ("CIM_Display20R.mof")
#pragma include ("UNIX_DesktopMonitor20R.mof")
#pragma include ("UNIX_FlatPanel20R.mof")
#pragma include ("UNIX_Processor20R.mof")
#pragma include ("UNIX_VideoHead20R.mof")
#pragma include ("UNIX_FingerprintReader20R.mof")
#pragma include ("UNIX_Door20R.mof")
#pragma include ("UNIX_SmartCard20R.mof")
#pragma include ("CIM_LogicalPort20R.mof")
#pragma include ("UNIX_NetworkPort20R.mof")
#pragma include ("UNIX_WiFiPort20R.mof")
#pragma include ("UNIX_EthernetPort20R.mof")
#pragma include ("UNIX_LLDPEthernetPort20R.mof")
#pragma include ("UNIX_DataCenterEthernetPort20R.mof")
#pragma include ("UNIX_SASPort20R.mof")
#pragma include ("UNIX_IBPort20R.mof")
#pragma include ("UNIX_FCPort20R.mof")
#pragma include ("UNIX_WirelessPort20R.mof")
#pragma include ("UNIX_TokenRingPort20R.mof")
#pragma include ("UNIX_DAPort20R.mof")
#pragma include ("UNIX_SerialPort20R.mof")
#pragma include ("UNIX_ATAPort20R.mof")
#pragma include ("UNIX_USBPort20R.mof")
#pragma include ("UNIX_PCIPort20R.mof")
#pragma include ("UNIX_SPIPort20R.mof")
#pragma include ("UNIX_ParallelPort20R.mof")
#pragma include ("UNIX_FibrePort20R.mof")
#pragma include ("UNIX_Watchdog20R.mof")
#pragma include ("CIM_NetworkAdapter20R.mof")
#pragma include ("UNIX_EthernetAdapter20R.mof")
#pragma include ("UNIX_TokenRingAdapter20R.mof")
#pragma include ("UNIX_FibreChannelAdapter20R.mof")
#pragma include ("UNIX_IndicatorLED20R.mof")
#pragma include ("UNIX_ElectricalSwitch20R.mof")
#pragma include ("UNIX_ProtocolController20R.mof")
#pragma include ("UNIX_SCSIProtocolController20R.mof")
#pragma include ("UNIX_WiFiRadio20R.mof")
#pragma include ("CIM_MediaTransferDevice20R.mof")
#pragma include ("UNIX_InterLibraryPort20R.mof")
#pragma include ("UNIX_LimitedAccessPort20R.mof")
#pragma include ("UNIX_SmartCardReader20R.mof")
#pragma include ("CIM_Controller20R.mof")
#pragma include ("CIM_PCIController20R.mof")
#pragma include ("CIM_PCIDevice20R.mof")
#pragma include ("UNIX_PCIBridge20R.mof")
#pragma include ("UNIX_PCIeSwitch20R.mof")
#pragma include ("UNIX_PortController20R.mof")
#pragma include ("UNIX_IBPortController20R.mof")
#pragma include ("UNIX_ParallelController20R.mof")
#pragma include ("UNIX_InfraredController20R.mof")
#pragma include ("UNIX_ManagementController20R.mof")
#pragma include ("UNIX_SSAController20R.mof")
#pragma include ("CIM_VideoController20R.mof")
#pragma include ("UNIX_AGPVideoController20R.mof")
#pragma include ("UNIX_PCVideoController20R.mof")
#pragma include ("UNIX_SerialController20R.mof")
#pragma include ("UNIX_DisplayController20R.mof")
#pragma include ("UNIX_AGPVideoDisplayController20R.mof")
#pragma include ("UNIX_USBController20R.mof")
#pragma include ("UNIX_IDEController20R.mof")
#pragma include ("UNIX_PCMCIAController20R.mof")
#pragma include ("UNIX_SCSIController20R.mof")
#pragma include ("UNIX_ESCONController20R.mof")
#pragma include ("CIM_LogicalModule20R.mof")
#pragma include ("UNIX_DeviceTray20R.mof")
#pragma include ("UNIX_PassThroughModule20R.mof")
#pragma include ("UNIX_AlarmDevice20R.mof")
#pragma include ("CIM_CoolingDevice20R.mof")
#pragma include ("UNIX_Fan20R.mof")
#pragma include ("UNIX_Refrigeration20R.mof")
#pragma include ("UNIX_HeatPipe20R.mof")
#pragma include ("UNIX_TPM20R.mof")
#pragma include ("UNIX_Scanner20R.mof")
#pragma include ("UNIX_Provider20R.mof")
#pragma include ("CIM_SystemResource20R.mof")
#pragma include ("UNIX_IRQ20R.mof")
#pragma include ("CIM_MemoryMappedIO20R.mof")
#pragma include ("UNIX_PortResource20R.mof")
#pragma include ("UNIX_MemoryResource20R.mof")
#pragma include ("UNIX_DMA20R.mof")
#pragma include ("CIM_Share20R.mof")
#pragma include ("CIM_FileShare20R.mof")
#pragma include ("UNIX_NFSShare20R.mof")
#pragma include ("UNIX_CIFSShare20R.mof")
#pragma include ("CIM_Log20R.mof")
#pragma include ("UNIX_MessageLog20R.mof")
#pragma include ("CIM_RecordLog20R.mof")
#pragma include ("UNIX_DiagnosticLog20R.mof")
#pragma include ("UNIX_DiagnosticsLog20R.mof")
#pragma include ("CIM_Service20R.mof")
#pragma include ("UNIX_FibreProtocolService20R.mof")
#pragma include ("UNIX_WakeUpService20R.mof")
#pragma include ("UNIX_VirtualSystemSnapshotService20R.mof")
#pragma include ("UNIX_ResourcePoolConfigurationService20R.mof")
#pragma include ("UNIX_FileSystemConfigurationService20R.mof")
#pragma include ("UNIX_HelpService20R.mof")
#pragma include ("UNIX_StorageRelocationService20R.mof")
#pragma include ("UNIX_MPLSService20R.mof")
#pragma include ("UNIX_PolicyActivationService20R.mof")
#pragma include ("UNIX_SCSIPathConfigurationService20R.mof")
#pragma include ("UNIX_BIOSService20R.mof")
#pragma include ("UNIX_PowerManagementService20R.mof")
#pragma include ("UNIX_NetworkPortConfigurationService20R.mof")
#pragma include ("UNIX_WiFiPortConfigurationService20R.mof")
#pragma include ("UNIX_VRFConfigurationService20R.mof")
#pragma include ("UNIX_ReplicationService20R.mof")
#pragma include ("CIM_SecurityService20R.mof")
#pragma include ("UNIX_AccountManagementService20R.mof")
#pragma include ("CIM_AuthenticationService20R.mof")
#pragma include ("UNIX_VerificationService20R.mof")
#pragma include ("CIM_CredentialManagementService20R.mof")
#pragma include ("UNIX_CertificateAuthority20R.mof")
#pragma include ("UNIX_Notary20R.mof")
#pragma include ("UNIX_KeyBasedCredentialManagementService20R.mof")
#pragma include ("UNIX_CertificateManagementService20R.mof")
#pragma include ("UNIX_KerberosKeyDistributionCenter20R.mof")
#pragma include ("CIM_LocalCredentialManagementService20R.mof")
#pragma include ("UNIX_PublicKeyManagementService20R.mof")
#pragma include ("UNIX_SharedSecretService20R.mof")
#pragma include ("UNIX_IdentityManagementService20R.mof")
#pragma include ("UNIX_StorageHardwareIDManagementService20R.mof")
#pragma include ("UNIX_AuthorizationService20R.mof")
#pragma include ("UNIX_PrivilegeManagementService20R.mof")
#pragma include ("UNIX_RoleBasedAuthorizationService20R.mof")
#pragma include ("UNIX_AccessControlService20R.mof")
#pragma include ("UNIX_WBEMServer20R.mof")
#pragma include ("UNIX_LaunchInContextService20R.mof")
#pragma include ("UNIX_VirtualSystemManagementService20R.mof")
#pragma include ("UNIX_MetricService20R.mof")
#pragma include ("UNIX_StorageNameBindingService20R.mof")
#pragma include ("UNIX_ZoneService20R.mof")
#pragma include ("UNIX_ControllerConfigurationService20R.mof")
#pragma include ("UNIX_GroupMaskingMappingService20R.mof")
#pragma include ("UNIX_DatabaseService20R.mof")
#pragma include ("UNIX_DiskPartitionConfigurationService20R.mof")
#pragma include ("UNIX_ConfigurationReportingService20R.mof")
#pragma include ("UNIX_PowerTopologyService20R.mof")
#pragma include ("UNIX_NetworkPolicyService20R.mof")
#pragma include ("UNIX_BasicExecutionService20R.mof")
#pragma include ("UNIX_SpareConfigurationService20R.mof")
#pragma include ("UNIX_StorageElementCompositionService20R.mof")
#pragma include ("UNIX_OpaqueManagementDataService20R.mof")
#pragma include ("UNIX_FingerprintMatchingService20R.mof")
#pragma include ("UNIX_ProtocolService20R.mof")
#pragma include ("UNIX_WBEMProtocolService20R.mof")
#pragma include ("UNIX_TierService20R.mof")
#pragma include ("UNIX_TierPolicyService20R.mof")
#pragma include ("UNIX_IndicationService20R.mof")
#pragma include ("UNIX_FileImportService20R.mof")
#pragma include ("UNIX_VTLStatisticalDataService20R.mof")
#pragma include ("UNIX_DropThresholdCalculationService20R.mof")
#pragma include ("CIM_ConditioningService20R.mof")
#pragma include ("CIM_MeterService20R.mof")
#pragma include ("UNIX_TokenBucketMeterService20R.mof")
#pragma include ("UNIX_EWMAMeterService20R.mof")
#pragma include ("UNIX_AverageRateMeterService20R.mof")
#pragma include ("CIM_MarkerService20R.mof")
#pragma include ("UNIX_ToSMarkerService20R.mof")
#pragma include ("UNIX_Priority8021QMarkerService20R.mof")
#pragma include ("UNIX_DSCPMarkerService20R.mof")
#pragma include ("UNIX_PreambleMarkerService20R.mof")
#pragma include ("UNIX_ClassifierService20R.mof")
#pragma include ("UNIX_ClassifierElement20R.mof")
#pragma include ("UNIX_PacketSchedulingService20R.mof")
#pragma include ("UNIX_NonWorkConservingSchedulingService20R.mof")
#pragma include ("CIM_DropperService20R.mof")
#pragma include ("UNIX_REDDropperService20R.mof")
#pragma include ("UNIX_HeadTailDropper20R.mof")
#pragma include ("UNIX_WeightedREDDropperService20R.mof")
#pragma include ("UNIX_QueuingService20R.mof")
#pragma include ("UNIX_BootService20R.mof")
#pragma include ("CIM_QoSService20R.mof")
#pragma include ("CIM_DiffServService20R.mof")
#pragma include ("UNIX_AFService20R.mof")
#pragma include ("UNIX_EFService20R.mof")
#pragma include ("UNIX_FlowService20R.mof")
#pragma include ("UNIX_Hdr8021PService20R.mof")
#pragma include ("UNIX_PrecedenceService20R.mof")
#pragma include ("UNIX_PrintService20R.mof")
#pragma include ("UNIX_TimeService20R.mof")
#pragma include ("UNIX_SoftwareInstallationService20R.mof")
#pragma include ("UNIX_VLANService20R.mof")
#pragma include ("UNIX_Specific802dot1QVLANService20R.mof")
#pragma include ("UNIX_PowerUtilizationManagementService20R.mof")
#pragma include ("UNIX_ClusteringService20R.mof")
#pragma include ("UNIX_SharedDeviceManagementService20R.mof")
#pragma include ("UNIX_BatchService20R.mof")
#pragma include ("UNIX_iSCSIConfigurationService20R.mof")
#pragma include ("UNIX_OOBAlertService20R.mof")
#pragma include ("UNIX_StorageConfigurationService20R.mof")
#pragma include ("UNIX_IPConfigurationService20R.mof")
#pragma include ("UNIX_VirtualSystemMigrationService20R.mof")
#pragma include ("UNIX_MPLSCrossConnect20R.mof")
#pragma include ("UNIX_PlatformWatchdogService20R.mof")
#pragma include ("CIM_DiagnosticService20R.mof")
#pragma include ("CIM_DiagnosticTest20R.mof")
#pragma include ("UNIX_FCHBADiagnosticTest20R.mof")
#pragma include ("UNIX_RAIDDiagnosticTest20R.mof")
#pragma include ("UNIX_CPUDiagnosticTest20R.mof")
#pragma include ("UNIX_EthernetNICDiagnosticTest20R.mof")
#pragma include ("UNIX_OpticalDriveDiagnosticTest20R.mof")
#pragma include ("UNIX_OpticalDriveDiagnosticSettingData20R.mof")
#pragma include ("UNIX_DiskDriveDiagnosticTest20R.mof")
#pragma include ("UNIX_IBSubnetManager20R.mof")
#pragma include ("CIM_WBEMService20R.mof")
#pragma include ("UNIX_ObjectManager20R.mof")
#pragma include ("UNIX_ObjectManagerAdapter20R.mof")
#pragma include ("UNIX_ProviderObjectManagerAdapter20R.mof")
#pragma include ("UNIX_ProtocolAdapter20R.mof")
#pragma include ("CIM_StatisticsService20R.mof")
#pragma include ("UNIX_FileSystemStatisticsService20R.mof")
#pragma include ("UNIX_BlockStatisticsService20R.mof")
#pragma include ("CIM_RedirectionService20R.mof")
#pragma include ("UNIX_USBRedirectionService20R.mof")
#pragma include ("UNIX_TextRedirectionService20R.mof")
#pragma include ("CIM_NetworkService20R.mof")
#pragma include ("CIM_RouteCalculationService20R.mof")
#pragma include ("UNIX_BGPService20R.mof")
#pragma include ("UNIX_OSPFService20R.mof")
#pragma include ("CIM_ForwardingService20R.mof")
#pragma include ("UNIX_NATService20R.mof")
#pragma include ("UNIX_TransparentBridgingService20R.mof")
#pragma include ("UNIX_SourceRoutingService20R.mof")
#pragma include ("UNIX_SpanningTreeService20R.mof")
#pragma include ("UNIX_SwitchService20R.mof")
#pragma include ("UNIX_FileExportService20R.mof")
#pragma include ("UNIX_OperatingSystem20R.mof")
#pragma include ("CIM_SoftwareResource20R.mof")
#pragma include ("UNIX_SWRFile20R.mof")
#pragma include ("UNIX_SWRPEP20R.mof")
#pragma include ("UNIX_SWRDatabase20R.mof")
#pragma include ("UNIX_ProviderLibrary20R.mof")
#pragma include ("CIM_ServiceAccessPoint20R.mof")
#pragma include ("UNIX_ClusteringSAP20R.mof")
#pragma include ("UNIX_CredentialManagementSAP20R.mof")
#pragma include ("UNIX_USBRedirectionSAP20R.mof")
#pragma include ("UNIX_IPNetworkConnection20R.mof")
#pragma include ("CIM_RemoteServiceAccessPoint20R.mof")
#pragma include ("UNIX_PolicyTransferServiceAccessPoint20R.mof")
#pragma include ("UNIX_LaunchInContextSAP20R.mof")
#pragma include ("UNIX_RemotePort20R.mof")
#pragma include ("UNIX_MPLSTunnelHop20R.mof")
#pragma include ("UNIX_SoftwareIdentityResource20R.mof")
#pragma include ("UNIX_KVMRedirectionSAP20R.mof")
#pragma include ("CIM_ProtocolEndpoint20R.mof")
#pragma include ("UNIX_DHCPProtocolEndpoint20R.mof")
#pragma include ("UNIX_SSHProtocolEndpoint20R.mof")
#pragma include ("UNIX_SCSIProtocolEndpoint20R.mof")
#pragma include ("UNIX_iSCSIProtocolEndpoint20R.mof")
#pragma include ("UNIX_CLPProtocolEndpoint20R.mof")
#pragma include ("UNIX_IPXProtocolEndpoint20R.mof")
#pragma include ("CIM_SecurityAssociationEndpoint20R.mof")
#pragma include ("UNIX_IPsecSAEndpoint20R.mof")
#pragma include ("UNIX_IKESAEndpoint20R.mof")
#pragma include ("UNIX_LANEndpoint20R.mof")
#pragma include ("UNIX_WiFiEndpoint20R.mof")
#pragma include ("UNIX_MPLSProtocolEndpoint20R.mof")
#pragma include ("UNIX_WirelessLANEndpoint20R.mof")
#pragma include ("UNIX_UDPProtocolEndpoint20R.mof")
#pragma include ("UNIX_TCPProtocolEndpoint20R.mof")
#pragma include ("CIM_OSPFProtocolEndpointBase20R.mof")
#pragma include ("UNIX_OSPFVirtualInterface20R.mof")
#pragma include ("UNIX_OSPFProtocolEndpoint20R.mof")
#pragma include ("UNIX_VLANEndpoint20R.mof")
#pragma include ("UNIX_LinkAggregator8023ad20R.mof")
#pragma include ("UNIX_ATAProtocolEndpoint20R.mof")
#pragma include ("CIM_IPProtocolEndpoint20R.mof")
#pragma include ("UNIX_IPEncapsulationInterface20R.mof")
#pragma include ("UNIX_IPSubinterface20R.mof")
#pragma include ("UNIX_SwitchVirtualInterface20R.mof")
#pragma include ("UNIX_IPLoopback20R.mof")
#pragma include ("UNIX_BGPProtocolEndpoint20R.mof")
#pragma include ("UNIX_SwitchPort20R.mof")
#pragma include ("UNIX_DNSProtocolEndpoint20R.mof")
#pragma include ("UNIX_LAGPort8023ad20R.mof")
#pragma include ("UNIX_BatchSAP20R.mof")
#pragma include ("UNIX_TextRedirectionSAP20R.mof")
#pragma include ("UNIX_MediaRedirectionSAP20R.mof")
#pragma include ("UNIX_PrintSAP20R.mof")
#pragma include ("UNIX_ServiceAccessURI20R.mof")
#pragma include ("UNIX_ObjectManagerCommunicationMechanism20R.mof")
#pragma include ("UNIX_CIMXMLCommunicationMechanism20R.mof")
#pragma include ("UNIX_VLAN20R.mof")
#pragma include ("UNIX_BootSAP20R.mof")
#pragma include ("CIM_Process20R.mof")
#pragma include ("UNIX_Process20R.mof")
#pragma include ("UNIX_ProcessorCore20R.mof")
#pragma include ("CIM_NetworkPipe20R.mof")
#pragma include ("UNIX_iSCSISession20R.mof")
#pragma include ("UNIX_iSCSIConnection20R.mof")
#pragma include ("UNIX_HardwareThread20R.mof")
#pragma include ("UNIX_FileSystem20R.mof")
#pragma include ("UNIX_DatabaseStorageArea20R.mof")
#pragma include ("CIM_LocalFileSystem20R.mof")
#pragma include ("UNIX_LocalFileSystem20R.mof")
#pragma include ("UNIX_RemoteFileSystem20R.mof")
#pragma include ("UNIX_NFS20R.mof")
#pragma include ("CIM_Thread20R.mof")
#pragma include ("UNIX_Thread20R.mof")
#pragma include ("UNIX_Account20R.mof")
#pragma include ("UNIX_BGPAttributes20R.mof")
#pragma include ("UNIX_ResourcePool20R.mof")
#pragma include ("UNIX_StoragePool20R.mof")
#pragma include ("UNIX_AdministrativeDistance20R.mof")
#pragma include ("UNIX_SoftwareFeature20R.mof")
#pragma include ("UNIX_VideoBIOSFeature20R.mof")
#pragma include ("UNIX_BIOSFeature20R.mof")
#pragma include ("UNIX_AGPSoftwareFeature20R.mof")
#pragma include ("UNIX_BGPRouteMap20R.mof")
#pragma include ("UNIX_OSPFAreaConfiguration20R.mof")
#pragma include ("CIM_LogicalFile20R.mof")
#pragma include ("UNIX_FIFOPipeFile20R.mof")
#pragma include ("CIM_Directory20R.mof")
#pragma include ("UNIX_Directory20R.mof")
#pragma include ("UNIX_DataFile20R.mof")
#pragma include ("UNIX_SymbolicLink20R.mof")
#pragma include ("CIM_DeviceFile20R.mof")
#pragma include ("UNIX_DeviceFile20R.mof")
#pragma include ("CIM_RedundancyGroup20R.mof")
#pragma include ("UNIX_SpareGroup20R.mof")
#pragma include ("UNIX_ExtraCapacityGroup20R.mof")
#pragma include ("UNIX_StorageRedundancyGroup20R.mof")
#pragma include ("UNIX_AccessControlInformation20R.mof")
#pragma include ("CIM_PrinterElement20R.mof")
#pragma include ("UNIX_PrintFinisher20R.mof")
#pragma include ("UNIX_PrintMarker20R.mof")
#pragma include ("UNIX_PrintSupply20R.mof")
#pragma include ("UNIX_PrintInterlock20R.mof")
#pragma include ("UNIX_PrintChannel20R.mof")
#pragma include ("UNIX_PrintInputTray20R.mof")
#pragma include ("UNIX_PrintOutputTray20R.mof")
#pragma include ("UNIX_PrintInterpreter20R.mof")
#pragma include ("UNIX_PrintMediaPath20R.mof")
#pragma include ("UNIX_SoftwareIdentity20R.mof")
#pragma include ("UNIX_SoftwareElement20R.mof")
#pragma include ("UNIX_BIOSElement20R.mof")
#pragma include ("UNIX_VideoBIOSElement20R.mof")
#pragma include ("CIM_Job20R.mof")
#pragma include ("UNIX_ConcreteJob20R.mof")
#pragma include ("UNIX_BatchJob20R.mof")
#pragma include ("UNIX_PrintJob20R.mof")
#pragma include ("UNIX_FilterList20R.mof")
#pragma include ("UNIX_RoutingPolicy20R.mof")
#pragma include ("UNIX_StaticForwardingEntry20R.mof")
#pragma include ("UNIX_File20R.mof")
#pragma include ("UNIX_BGPPathAttributes20R.mof")
#pragma include ("UNIX_OtherRoleInformation20R.mof")
#pragma include ("UNIX_OtherGroupInformation20R.mof")
#pragma include ("CIM_Identity20R.mof")
#pragma include ("UNIX_IPNetworkIdentity20R.mof")
#pragma include ("UNIX_RemoteIdentity20R.mof")
#pragma include ("UNIX_StorageHardwareID20R.mof")
#pragma include ("UNIX_GatewayPathID20R.mof")
#pragma include ("CIM_RecordForLog20R.mof")
#pragma include ("UNIX_LogRecord20R.mof")
#pragma include ("UNIX_LogEntry20R.mof")
#pragma include ("UNIX_PrintAlertRecord20R.mof")
#pragma include ("CIM_DiagnosticRecord20R.mof")
#pragma include ("UNIX_DiagnosticServiceRecord20R.mof")
#pragma include ("UNIX_DiagnosticCompletionRecord20R.mof")
#pragma include ("UNIX_DiagnosticSettingDataRecord20R.mof")
#pragma include ("UNIX_DiagnosticSettingRecord20R.mof")
#pragma include ("UNIX_NextHopRoute20R.mof")
#pragma include ("UNIX_NextHopIPRoute20R.mof")
#pragma include ("CIM_View20R.mof")
#pragma include ("UNIX_PhysicalComputerSystemView20R.mof")
#pragma include ("UNIX_StoragePoolView20R.mof")
#pragma include ("CIM_LogicalDeviceView20R.mof")
#pragma include ("UNIX_MappingProtocolControllerView20R.mof")
#pragma include ("UNIX_VolumeView20R.mof")
#pragma include ("UNIX_DiskDriveView20R.mof")
#pragma include ("UNIX_ReplicaPairView20R.mof")
#pragma include ("CIM_BaseMetricValue20R.mof")
#pragma include ("UNIX_DiscreteMetricValue20R.mof")
#pragma include ("UNIX_AggregationMetricValue20R.mof")
#pragma include ("UNIX_SecuritySensitivity20R.mof")
#pragma include ("CIM_BIOSAttribute20R.mof")
#pragma include ("UNIX_BIOSPassword20R.mof")
#pragma include ("UNIX_BIOSEnumeration20R.mof")
#pragma include ("UNIX_BIOSString20R.mof")
#pragma include ("UNIX_BIOSInteger20R.mof")
#pragma include ("CIM_Capabilities20R.mof")
#pragma include ("UNIX_RedundancySetCapabilities20R.mof")
#pragma include ("UNIX_JobCapabilities20R.mof")
#pragma include ("UNIX_DiagnosticServiceJobCapabilities20R.mof")
#pragma include ("CIM_StatisticsCapabilities20R.mof")
#pragma include ("UNIX_BlockStatisticsCapabilities20R.mof")
#pragma include ("UNIX_FileSystemStatisticsCapabilities20R.mof")
#pragma include ("UNIX_VirtualSystemSnapshotServiceCapabilities20R.mof")
#pragma include ("CIM_EnabledLogicalElementCapabilities20R.mof")
#pragma include ("CIM_RedirectionServiceCapabilities20R.mof")
#pragma include ("UNIX_USBRedirectionCapabilities20R.mof")
#pragma include ("UNIX_MediaRedirectionCapabilities20R.mof")
#pragma include ("UNIX_PowerUtilizationManagementCapabilities20R.mof")
#pragma include ("UNIX_VirtualSystemManagementCapabilities20R.mof")
#pragma include ("UNIX_WiFiEndpointCapabilities20R.mof")
#pragma include ("CIM_ProtocolServiceCapabilities20R.mof")
#pragma include ("CIM_WBEMProtocolServiceCapabilities20R.mof")
#pragma include ("UNIX_WSManagementCapabilities20R.mof")
#pragma include ("UNIX_CIMXMLCapabilities20R.mof")
#pragma include ("UNIX_SSHCapabilities20R.mof")
#pragma include ("UNIX_CLPCapabilities20R.mof")
#pragma include ("UNIX_RecordLogCapabilities20R.mof")
#pragma include ("UNIX_LaunchInContextCapabilities20R.mof")
#pragma include ("UNIX_AccountManagementCapabilities20R.mof")
#pragma include ("UNIX_PowerTopologyCapabilities20R.mof")
#pragma include ("UNIX_AccountCapabilities20R.mof")
#pragma include ("CIM_LogicalPortCapabilities20R.mof")
#pragma include ("CIM_NetworkPortCapabilities20R.mof")
#pragma include ("UNIX_WiFiPortCapabilities20R.mof")
#pragma include ("UNIX_FCPortCapabilities20R.mof")
#pragma include ("UNIX_OpaqueManagementDataCapabilities20R.mof")
#pragma include ("UNIX_OperatingSystemCapabilities20R.mof")
#pragma include ("UNIX_NetworkPolicyServiceCapabilities20R.mof")
#pragma include ("UNIX_LoadBalancerServiceCapabilities20R.mof")
#pragma include ("UNIX_FCSwitchCapabilities20R.mof")
#pragma include ("UNIX_WBEMServerCapabilities20R.mof")
#pragma include ("UNIX_IndicatorLEDCapabilities20R.mof")
#pragma include ("UNIX_CredentialManagementCapabilities20R.mof")
#pragma include ("UNIX_CertificateManagementCapabilities20R.mof")
#pragma include ("UNIX_BootServiceCapabilities20R.mof")
#pragma include ("UNIX_ProcessorCapabilities20R.mof")
#pragma include ("UNIX_TPMCapabilities20R.mof")
#pragma include ("UNIX_AlarmDeviceCapabilities20R.mof")
#pragma include ("UNIX_DHCPCapabilities20R.mof")
#pragma include ("UNIX_MetricServiceCapabilities20R.mof")
#pragma include ("UNIX_FingerprintMatchingServiceCapabilities20R.mof")
#pragma include ("UNIX_PlatformWatchdogServiceCapabilities20R.mof")
#pragma include ("UNIX_ImportedFileShareCapabilities20R.mof")
#pragma include ("UNIX_PhysicalAssetCapabilities20R.mof")
#pragma include ("UNIX_DeviceSharingCapabilities20R.mof")
#pragma include ("UNIX_AllocationCapabilities20R.mof")
#pragma include ("UNIX_PrintServiceCapabilities20R.mof")
#pragma include ("UNIX_OSPFServiceCapabilities20R.mof")
#pragma include ("UNIX_ZoneCapabilities20R.mof")
#pragma include ("UNIX_StorageNameBindingCapabilities20R.mof")
#pragma include ("UNIX_VLANSystemCapabilities20R.mof")
#pragma include ("UNIX_IndicationServiceCapabilities20R.mof")
#pragma include ("UNIX_BIOSServiceCapabilities20R.mof")
#pragma include ("UNIX_ViewCapabilities20R.mof")
#pragma include ("UNIX_FileImportCapabilities20R.mof")
#pragma include ("UNIX_ExportedFileShareCapabilities20R.mof")
#pragma include ("UNIX_VTLStatisticalDataServiceCapabilities20R.mof")
#pragma include ("UNIX_QueryCapabilities20R.mof")
#pragma include ("UNIX_LocalizationCapabilities20R.mof")
#pragma include ("UNIX_PrivilegeManagementCapabilities20R.mof")
#pragma include ("UNIX_RoleBasedManagementCapabilities20R.mof")
#pragma include ("UNIX_SoftwareInstallationServiceCapabilities20R.mof")
#pragma include ("UNIX_SCSIMultipathConfigurationCapabilities20R.mof")
#pragma include ("UNIX_FileSystemReplicationCapabilities20R.mof")
#pragma include ("CIM_DiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_RAIDDiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_EthernetNICDiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_CPUDiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_DiskDriveDiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_FCHBADiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_OpticalDriveDiagnosticServiceCapabilities20R.mof")
#pragma include ("UNIX_iSCSIConfigurationCapabilities20R.mof")
#pragma include ("UNIX_ComputerSystemNodeCapabilities20R.mof")
#pragma include ("UNIX_MPLSCapabilities20R.mof")
#pragma include ("UNIX_CommonDatabaseCapabilities20R.mof")
#pragma include ("UNIX_RelationalDatabaseCapabilities20R.mof")
#pragma include ("UNIX_FileSystemConfigurationCapabilities20R.mof")
#pragma include ("UNIX_FileSystemReplicationServiceCapabilities20R.mof")
#pragma include ("UNIX_ProtocolControllerMaskingCapabilities20R.mof")
#pragma include ("UNIX_GroupMaskingMappingCapabilities20R.mof")
#pragma include ("UNIX_FileSystemCapabilities20R.mof")
#pragma include ("UNIX_IEEE8021xCapabilities20R.mof")
#pragma include ("UNIX_ReplicationServiceCapabilities20R.mof")
#pragma include ("UNIX_LAGControlCapabilities20R.mof")
#pragma include ("UNIX_ResourcePoolConfigurationCapabilities20R.mof")
#pragma include ("UNIX_PowerManagementCapabilities20R.mof")
#pragma include ("UNIX_VirtualSystemSnapshotCapabilities20R.mof")
#pragma include ("UNIX_iSCSICapabilities20R.mof")
#pragma include ("UNIX_ImplementationCapabilities20R.mof")
#pragma include ("UNIX_StorageLibraryCapabilities20R.mof")
#pragma include ("UNIX_VLANEndpointCapabilities20R.mof")
#pragma include ("UNIX_ProviderCapabilities20R.mof")
#pragma include ("UNIX_StorageServerAsymmetryCapabilities20R.mof")
#pragma include ("UNIX_DiskPartitionConfigurationCapabilities20R.mof")
#pragma include ("UNIX_StorageReplicationCapabilities20R.mof")
#pragma include ("UNIX_StorageConfigurationCapabilities20R.mof")
#pragma include ("UNIX_TierServiceCapabilities20R.mof")
#pragma include ("UNIX_TierPolicyServiceCapabilities20R.mof")
#pragma include ("UNIX_StorageCapabilities20R.mof")
#pragma include ("UNIX_StorageTierCapabilities20R.mof")
#pragma include ("UNIX_SpareConfigurationCapabilities20R.mof")
#pragma include ("UNIX_FileExportCapabilities20R.mof")
#pragma include ("UNIX_VirtualSystemMigrationCapabilities20R.mof")
#pragma include ("UNIX_StorageElementCompositionCapabilities20R.mof")
#pragma include ("UNIX_WBEMServerNamespace20R.mof")
#pragma include ("UNIX_FileSystemStatisticsManifest20R.mof")
#pragma include ("CIM_SchedulingElement20R.mof")
#pragma include ("UNIX_PrioritySchedulingElement20R.mof")
#pragma include ("UNIX_BoundedPrioritySchedulingElement20R.mof")
#pragma include ("UNIX_AllocationSchedulingElement20R.mof")
#pragma include ("UNIX_WRRSchedulingElement20R.mof")
#pragma include ("UNIX_ReplacementFRU20R.mof")
#pragma include ("UNIX_MethodResult20R.mof")
#pragma include ("UNIX_RegisteredSpecification20R.mof")
#pragma include ("UNIX_RegisteredProfile20R.mof")
#pragma include ("UNIX_RegisteredSubProfile20R.mof")
#pragma include ("CIM_Credential20R.mof")
#pragma include ("UNIX_UnsignedPublicKey20R.mof")
#pragma include ("UNIX_NamedSharedIKESecret20R.mof")
#pragma include ("UNIX_FingerprintImage20R.mof")
#pragma include ("UNIX_UnsignedCredential20R.mof")
#pragma include ("UNIX_SharedCredential20R.mof")
#pragma include ("UNIX_KerberosCredential20R.mof")
#pragma include ("UNIX_KerberosTicket20R.mof")
#pragma include ("UNIX_NamedCredential20R.mof")
#pragma include ("CIM_SignedCredential20R.mof")
#pragma include ("CIM_X509Infrastructure20R.mof")
#pragma include ("UNIX_X509Certificate20R.mof")
#pragma include ("UNIX_X509CRL20R.mof")
#pragma include ("UNIX_PublicKeyCertificate20R.mof")
#pragma include ("UNIX_FingerprintTemplate20R.mof")
#pragma include ("UNIX_SharedSecret20R.mof")
#pragma include ("CIM_Collection20R.mof")
#pragma include ("UNIX_TopologyGraph20R.mof")
#pragma include ("UNIX_ConcreteCollection20R.mof")
#pragma include ("UNIX_StatusCollection20R.mof")
#pragma include ("CIM_CollectionOfMSEs20R.mof")
#pragma include ("CIM_LogicalNetwork20R.mof")
#pragma include ("UNIX_IPXNetwork20R.mof")
#pragma include ("UNIX_LANSegment20R.mof")
#pragma include ("UNIX_IPSubnet20R.mof")
#pragma include ("UNIX_BGPPeerGroup20R.mof")
#pragma include ("UNIX_BufferPool20R.mof")
#pragma include ("UNIX_MPLSBuffers20R.mof")
#pragma include ("UNIX_IPAddressRange20R.mof")
#pragma include ("UNIX_BGPCluster20R.mof")
#pragma include ("UNIX_DiskGroup20R.mof")
#pragma include ("UNIX_Role20R.mof")
#pragma include ("UNIX_ReplacementSet20R.mof")
#pragma include ("CIM_SystemSpecificCollection20R.mof")
#pragma include ("UNIX_StatisticsCollection20R.mof")
#pragma include ("UNIX_QueryStatisticsCollection20R.mof")
#pragma include ("UNIX_TargetPortGroup20R.mof")
#pragma include ("CIM_ConnectivityCollection20R.mof")
#pragma include ("UNIX_Zone20R.mof")
#pragma include ("UNIX_ZoneSet20R.mof")
#pragma include ("UNIX_LANConnectivitySegment20R.mof")
#pragma include ("UNIX_IPXConnectivityNetwork20R.mof")
#pragma include ("UNIX_OSPFLink20R.mof")
#pragma include ("UNIX_NetworkVLAN20R.mof")
#pragma include ("UNIX_IPConnectivitySubnet20R.mof")
#pragma include ("UNIX_DeviceConnectivityCollection20R.mof")
#pragma include ("UNIX_RemoteReplicationCollection20R.mof")
#pragma include ("UNIX_StorageTier20R.mof")
#pragma include ("UNIX_FileSystemStatisticsManifestCollection20R.mof")
#pragma include ("UNIX_LogicalPortGroup20R.mof")
#pragma include ("UNIX_PCIPortGroup20R.mof")
#pragma include ("UNIX_SCSITargetPortGroup20R.mof")
#pragma include ("UNIX_VirtualRoutingAndForwardingTable20R.mof")
#pragma include ("UNIX_StorageResourceLoadGroup20R.mof")
#pragma include ("CIM_MaskingGroup20R.mof")
#pragma include ("UNIX_InitiatorMaskingGroup20R.mof")
#pragma include ("UNIX_TargetMaskingGroup20R.mof")
#pragma include ("UNIX_DeviceMaskingGroup20R.mof")
#pragma include ("UNIX_FailoverStorageExtentsCollection20R.mof")
#pragma include ("UNIX_PolicyRoleCollection20R.mof")
#pragma include ("UNIX_BlockStatisticsManifestCollection20R.mof")
#pragma include ("UNIX_RedundancySet20R.mof")
#pragma include ("UNIX_StorageRedundancySet20R.mof")
#pragma include ("UNIX_RangeOfIPAddresses20R.mof")
#pragma include ("UNIX_NamedAddressCollection20R.mof")
#pragma include ("UNIX_ReplicationGroup20R.mof")
#pragma include ("UNIX_InstalledProduct20R.mof")
#pragma include ("UNIX_CredentialStore20R.mof")
#pragma include ("UNIX_Keystore20R.mof")
#pragma include ("UNIX_FilterCollection20R.mof")
#pragma include ("UNIX_Group20R.mof")
#pragma include ("UNIX_Profile20R.mof")
#pragma include ("UNIX_BatchJobGroup20R.mof")
#pragma include ("UNIX_Configuration20R.mof")
#pragma include ("CIM_Check20R.mof")
#pragma include ("UNIX_ArchitectureCheck20R.mof")
#pragma include ("UNIX_FileSpecification20R.mof")
#pragma include ("UNIX_SettingCheck20R.mof")
#pragma include ("UNIX_VersionCompatibilityCheck20R.mof")
#pragma include ("UNIX_SwapSpaceCheck20R.mof")
#pragma include ("UNIX_SoftwareElementVersionCheck20R.mof")
#pragma include ("UNIX_OSVersionCheck20R.mof")
#pragma include ("UNIX_DirectorySpecification20R.mof")
#pragma include ("UNIX_DiskSpaceCheck20R.mof")
#pragma include ("UNIX_MemoryCheck20R.mof")
#pragma include ("UNIX_OtherPersonInformation20R.mof")
#pragma include ("UNIX_SupportAccess20R.mof")
#pragma include ("UNIX_IndicationFilter20R.mof")
#pragma include ("UNIX_Location20R.mof")
#pragma include ("CIM_Action20R.mof")
#pragma include ("UNIX_RebootAction20R.mof")
#pragma include ("CIM_DirectoryAction20R.mof")
#pragma include ("UNIX_CreateDirectoryAction20R.mof")
#pragma include ("UNIX_RemoveDirectoryAction20R.mof")
#pragma include ("CIM_FileAction20R.mof")
#pragma include ("UNIX_CopyFileAction20R.mof")
#pragma include ("UNIX_RemoveFileAction20R.mof")
#pragma include ("UNIX_ModifySettingAction20R.mof")
#pragma include ("UNIX_ExecuteProgram20R.mof")
#pragma include ("UNIX_Product20R.mof")
#pragma include ("CIM_StatisticalData20R.mof")
#pragma include ("UNIX_VLANStatistics20R.mof")
#pragma include ("UNIX_JobProcessingStatistics20R.mof")
#pragma include ("CIM_SWRStatistics20R.mof")
#pragma include ("UNIX_SWRAllocationStatistics20R.mof")
#pragma include ("UNIX_SWRIOStatistics20R.mof")
#pragma include ("UNIX_MPLSSegmentStats20R.mof")
#pragma include ("UNIX_VTLStatisticalData20R.mof")
#pragma include ("UNIX_FCPortRateStatistics20R.mof")
#pragma include ("UNIX_BGPEndpointStatistics20R.mof")
#pragma include ("UNIX_SAEndpointConnectionStatistics20R.mof")
#pragma include ("UNIX_FileSystemStatisticalData20R.mof")
#pragma include ("UNIX_iSCSISessionFailures20R.mof")
#pragma include ("UNIX_iSCSILoginStatistics20R.mof")
#pragma include ("UNIX_iSCSISessionStatistics20R.mof")
#pragma include ("UNIX_DatabaseServiceStatistics20R.mof")
#pragma include ("UNIX_MPLSTunnelStats20R.mof")
#pragma include ("UNIX_MediaAccessStatData20R.mof")
#pragma include ("UNIX_FingerprintMatchingStatistics20R.mof")
#pragma include ("UNIX_LACPPortStatistics20R.mof")
#pragma include ("CIM_ImagingStatisticalData20R.mof")
#pragma include ("UNIX_ImagingMonitorStatisticalData20R.mof")
#pragma include ("UNIX_ImagingWorkStatisticalData20R.mof")
#pragma include ("UNIX_ImagingMediaUsedStatisticalData20R.mof")
#pragma include ("UNIX_MPLSProtocolEndpointStats20R.mof")
#pragma include ("UNIX_CIMOMStatisticalData20R.mof")
#pragma include ("UNIX_DeviceErrorData20R.mof")
#pragma include ("UNIX_MediaPhysicalStatData20R.mof")
#pragma include ("UNIX_LabelReaderStatData20R.mof")
#pragma include ("UNIX_TCPStatisticalData20R.mof")
#pragma include ("UNIX_VTLResourceUsage20R.mof")
#pragma include ("UNIX_MPLSPerformance20R.mof")
#pragma include ("UNIX_PoweredStatisticalData20R.mof")
#pragma include ("UNIX_TapeDriveResourceUsage20R.mof")
#pragma include ("CIM_ProtocolEndpointStatistics20R.mof")
#pragma include ("UNIX_TCPEndpointStatistics20R.mof")
#pragma include ("UNIX_IPEndpointStatistics20R.mof")
#pragma include ("UNIX_DatabaseResourceStatistics20R.mof")
#pragma include ("UNIX_CommonDatabaseStatistics20R.mof")
#pragma include ("UNIX_QueueStatisticalData20R.mof")
#pragma include ("UNIX_BlockStorageStatisticalData20R.mof")
#pragma include ("CIM_NetworkPortStatistics20R.mof")
#pragma include ("UNIX_TokenRingPortStatistics20R.mof")
#pragma include ("UNIX_FCPortStatistics20R.mof")
#pragma include ("UNIX_FCPortResourceUsage20R.mof")
#pragma include ("UNIX_EthernetPortStatistics20R.mof")
#pragma include ("UNIX_LLDPEthernetPortStatistics20R.mof")
#pragma include ("UNIX_DataCenterEthernetPortStatistics20R.mof")
#pragma include ("UNIX_IBPortStatistics20R.mof")
#pragma include ("UNIX_StatisticalRuntimeOverview20R.mof")
#pragma include ("CIM_PhysicalCapacity20R.mof")
#pragma include ("UNIX_MemoryCapacity20R.mof")
#pragma include ("UNIX_ConfigurationCapacity20R.mof")
#pragma include ("UNIX_StorageError20R.mof")
#pragma include ("UNIX_MemoryError20R.mof")
#pragma include ("UNIX_OtherOrganizationInformation20R.mof")
#pragma include ("UNIX_MethodParameters20R.mof")
#pragma include ("UNIX_SystemConfiguration20R.mof")
#pragma include ("UNIX_FRU20R.mof")
#pragma include ("CIM_OrganizationalEntity20R.mof")
#pragma include ("UNIX_OrgUnit20R.mof")
#pragma include ("CIM_UserEntity20R.mof")
#pragma include ("UNIX_UserContact20R.mof")
#pragma include ("UNIX_Person20R.mof")
#pragma include ("UNIX_UsersAccess20R.mof")
#pragma include ("UNIX_Organization20R.mof")
#pragma include ("CIM_BaseMetricDefinition20R.mof")
#pragma include ("UNIX_AggregationMetricDefinition20R.mof")
#pragma include ("UNIX_DiscreteMetricDefinition20R.mof")
#pragma include ("UNIX_MetricDefinition20R.mof")
#pragma include ("UNIX_SystemIdentification20R.mof")
#pragma include ("UNIX_TraceLevelType20R.mof")
#pragma include ("UNIX_Namespace20R.mof")
#pragma include ("UNIX_OtherOrgUnitInformation20R.mof")
#pragma include ("UNIX_BlockStatisticsManifest20R.mof")
#pragma include ("CIM_Setting20R.mof")
#pragma include ("UNIX_VideoControllerResolution20R.mof")
#pragma include ("UNIX_DiagnosticSetting20R.mof")
#pragma include ("UNIX_MonitorResolution20R.mof")
#pragma include ("UNIX_TimeZone20R.mof")
#pragma include ("UNIX_SystemSetting20R.mof")
#pragma include ("CIM_Policy20R.mof")
#pragma include ("UNIX_NetworkPolicyAction20R.mof")
#pragma include ("CIM_PolicyAction20R.mof")
#pragma include ("UNIX_VendorPolicyAction20R.mof")
#pragma include ("CIM_SAAction20R.mof")
#pragma include ("CIM_SANegotiationAction20R.mof")
#pragma include ("UNIX_IKEAction20R.mof")
#pragma include ("CIM_IPsecAction20R.mof")
#pragma include ("UNIX_IPsecTransportAction20R.mof")
#pragma include ("UNIX_IPsecTunnelAction20R.mof")
#pragma include ("CIM_SAStaticAction20R.mof")
#pragma include ("CIM_PreconfiguredSAAction20R.mof")
#pragma include ("UNIX_PreconfiguredTransportAction20R.mof")
#pragma include ("UNIX_PreconfiguredTunnelAction20R.mof")
#pragma include ("UNIX_RejectConnectionAction20R.mof")
#pragma include ("UNIX_MethodAction20R.mof")
#pragma include ("UNIX_NetworkPacketAction20R.mof")
#pragma include ("UNIX_CompoundPolicyAction20R.mof")
#pragma include ("CIM_PolicyCondition20R.mof")
#pragma include ("UNIX_PacketFilterCondition20R.mof")
#pragma include ("UNIX_CompoundPolicyCondition20R.mof")
#pragma include ("UNIX_QueryCondition20R.mof")
#pragma include ("CIM_AuthenticationCondition20R.mof")
#pragma include ("UNIX_DocumentAuthentication20R.mof")
#pragma include ("UNIX_NetworkingIDAuthentication20R.mof")
#pragma include ("UNIX_KerberosAuthentication20R.mof")
#pragma include ("UNIX_BiometricAuthentication20R.mof")
#pragma include ("UNIX_PublicPrivateKeyAuthentication20R.mof")
#pragma include ("UNIX_PhysicalCredentialAuthentication20R.mof")
#pragma include ("UNIX_SharedSecretAuthentication20R.mof")
#pragma include ("UNIX_AccountAuthentication20R.mof")
#pragma include ("UNIX_PolicyTimePeriodCondition20R.mof")
#pragma include ("UNIX_VendorPolicyCondition20R.mof")
#pragma include ("UNIX_NetworkPolicyCondition20R.mof")
#pragma include ("CIM_PolicySet20R.mof")
#pragma include ("UNIX_AccessControlPolicy20R.mof")
#pragma include ("UNIX_PolicyGroup20R.mof")
#pragma include ("UNIX_AccessControlPolicyGroup20R.mof")
#pragma include ("CIM_PolicyRule20R.mof")
#pragma include ("UNIX_AuthorizationRule20R.mof")
#pragma include ("UNIX_NetworkPolicyRule20R.mof")
#pragma include ("CIM_SARule20R.mof")
#pragma include ("UNIX_IPsecRule20R.mof")
#pragma include ("UNIX_IKERule20R.mof")
#pragma include ("UNIX_AuthenticationRule20R.mof")
#pragma include ("UNIX_TierPolicyRule20R.mof")
#pragma include ("UNIX_Privilege20R.mof")
#pragma include ("UNIX_AuthorizedPrivilege20R.mof")
#pragma include ("CIM_AbstractComponent20R.mof")
#pragma include ("UNIX_ExtentComponentView20R.mof")
#pragma include ("CIM_Component20R.mof")
#pragma include ("UNIX_PrintJobFile20R.mof")
#pragma include ("UNIX_MPLSLSPInLSP20R.mof")
#pragma include ("UNIX_SoftwareElementComponent20R.mof")
#pragma include ("UNIX_DirectoryContainsFile20R.mof")
#pragma include ("UNIX_BGPServiceAttributes20R.mof")
#pragma include ("UNIX_FileStorage20R.mof")
#pragma include ("UNIX_CollectionOfSensors20R.mof")
#pragma include ("UNIX_ProductComponent20R.mof")
#pragma include ("UNIX_EndpointInArea20R.mof")
#pragma include ("UNIX_DatabaseFile20R.mof")
#pragma include ("CIM_SystemComponent20R.mof")
#pragma include ("CIM_SystemDevice20R.mof")
#pragma include ("UNIX_SystemSCSIProtocolController20R.mof")
#pragma include ("UNIX_ComputerSystemMemory20R.mof")
#pragma include ("UNIX_SystemFCPort20R.mof")
#pragma include ("UNIX_ComputerSystemProcessor20R.mof")
#pragma include ("UNIX_SystemBIOS20R.mof")
#pragma include ("UNIX_DomainMemberCS20R.mof")
#pragma include ("UNIX_ASBGPEndpoints20R.mof")
#pragma include ("UNIX_AccountOnSystem20R.mof")
#pragma include ("UNIX_ContainedDomain20R.mof")
#pragma include ("UNIX_RoutingProtocolDomainInAS20R.mof")
#pragma include ("CIM_ResourceOfSystem20R.mof")
#pragma include ("CIM_ComputerSystemResource20R.mof")
#pragma include ("UNIX_ComputerSystemIRQ20R.mof")
#pragma include ("UNIX_ComputerSystemMappedIO20R.mof")
#pragma include ("UNIX_ComputerSystemDMA20R.mof")
#pragma include ("UNIX_Confederation20R.mof")
#pragma include ("UNIX_HostedResourcePool20R.mof")
#pragma include ("UNIX_HostedStoragePool20R.mof")
#pragma include ("UNIX_RoutersInAS20R.mof")
#pragma include ("UNIX_PolicyContainerInPolicyContainer20R.mof")
#pragma include ("UNIX_ComponentCS20R.mof")
#pragma include ("UNIX_SystemPartition20R.mof")
#pragma include ("UNIX_FilterEntryInSystem20R.mof")
#pragma include ("UNIX_ApplicationSystemSoftwareFeature20R.mof")
#pragma include ("UNIX_PolicyRepositoryInPolicyRepository20R.mof")
#pragma include ("UNIX_HostedFileSystem20R.mof")
#pragma include ("UNIX_InstalledOS20R.mof")
#pragma include ("UNIX_FilterListInSystem20R.mof")
#pragma include ("UNIX_BGPRouteMapsInRoutingPolicy20R.mof")
#pragma include ("UNIX_OSProcess20R.mof")
#pragma include ("UNIX_ListsInRoutingPolicy20R.mof")
#pragma include ("CIM_PolicyComponent20R.mof")
#pragma include ("UNIX_PolicyGroupInPolicyGroup20R.mof")
#pragma include ("CIM_PolicyConditionStructure20R.mof")
#pragma include ("UNIX_PolicyConditionInPolicyCondition20R.mof")
#pragma include ("UNIX_PolicyConditionInPolicyRule20R.mof")
#pragma include ("UNIX_PacketConditionInSARule20R.mof")
#pragma include ("UNIX_PolicySetComponent20R.mof")
#pragma include ("UNIX_PolicySetValidityPeriod20R.mof")
#pragma include ("UNIX_PolicyRuleInPolicyGroup20R.mof")
#pragma include ("CIM_PolicyActionStructure20R.mof")
#pragma include ("UNIX_PolicyActionInPolicyAction20R.mof")
#pragma include ("UNIX_PolicyActionInPolicyRule20R.mof")
#pragma include ("UNIX_PolicyRuleValidityPeriod20R.mof")
#pragma include ("UNIX_ProcessThread20R.mof")
#pragma include ("UNIX_LinkHasConnector20R.mof")
#pragma include ("UNIX_SoftwareFeatureComponent20R.mof")
#pragma include ("UNIX_NetworkPipeComposition20R.mof")
#pragma include ("UNIX_OperatingSystemSoftwareFeature20R.mof")
#pragma include ("UNIX_SettingsDefineCapabilities20R.mof")
#pragma include ("UNIX_VirtualSystemSettingDataComponent20R.mof")
#pragma include ("UNIX_AssociatedElementTier20R.mof")
#pragma include ("UNIX_ContainedTransform20R.mof")
#pragma include ("UNIX_ElementInSchedulingService20R.mof")
#pragma include ("UNIX_SoftwareIdentityComponent20R.mof")
#pragma include ("CIM_ServiceComponent20R.mof")
#pragma include ("UNIX_SwitchServiceTransparentBridging20R.mof")
#pragma include ("UNIX_SwitchServiceVLAN20R.mof")
#pragma include ("UNIX_QoSSubService20R.mof")
#pragma include ("UNIX_QoSConditioningSubService20R.mof")
#pragma include ("UNIX_SwitchServiceSpanningTree20R.mof")
#pragma include ("UNIX_SwitchServiceSourceRouting20R.mof")
#pragma include ("UNIX_ClassifierElementInClassifierService20R.mof")
#pragma include ("UNIX_DiagnosticTestInPackage20R.mof")
#pragma include ("CIM_Container20R.mof")
#pragma include ("UNIX_PackageInChassis20R.mof")
#pragma include ("UNIX_CardOnCard20R.mof")
#pragma include ("UNIX_ConnectorOnPackage20R.mof")
#pragma include ("UNIX_ChassisInRack20R.mof")
#pragma include ("UNIX_PackagedComponent20R.mof")
#pragma include ("UNIX_MemoryOnCard20R.mof")
#pragma include ("UNIX_ContainedLocation20R.mof")
#pragma include ("UNIX_PrinterComponent20R.mof")
#pragma include ("UNIX_DatabaseContainsTable20R.mof")
#pragma include ("UNIX_EntriesInFilterList20R.mof")
#pragma include ("UNIX_DatabaseStorage20R.mof")
#pragma include ("UNIX_ApplicationSystemHierarchy20R.mof")
#pragma include ("UNIX_FilteredBGPAttributes20R.mof")
#pragma include ("UNIX_ContainedProposal20R.mof")
#pragma include ("UNIX_OrderedComponent20R.mof")
#pragma include ("UNIX_AssociatedRemainingExtent20R.mof")
#pragma include ("UNIX_ModulePort20R.mof")
#pragma include ("UNIX_ProcessOfJob20R.mof")
#pragma include ("UNIX_ConcreteComponent20R.mof")
#pragma include ("CIM_ProductElementComponent20R.mof")
#pragma include ("UNIX_ProductSoftwareComponent20R.mof")
#pragma include ("UNIX_ProductPhysicalComponent20R.mof")
#pragma include ("UNIX_ProductServiceComponent20R.mof")
#pragma include ("UNIX_ProviderInProviderLibrary20R.mof")
#pragma include ("CIM_RedundancyComponent20R.mof")
#pragma include ("CIM_ExtentRedundancyComponent20R.mof")
#pragma include ("UNIX_AggregateRedundancyComponent20R.mof")
#pragma include ("UNIX_PExtentRedundancyComponent20R.mof")
#pragma include ("UNIX_NetworkAdapterRedundancyComponent20R.mof")
#pragma include ("UNIX_AssociatedComponentExtent20R.mof")
#pragma include ("CIM_SoftwareFeatureSoftwareElements20R.mof")
#pragma include ("UNIX_BIOSFeatureBIOSElements20R.mof")
#pragma include ("UNIX_VideoBIOSFeatureVideoBIOSElements20R.mof")
#pragma include ("UNIX_DriveComponentViewView20R.mof")
#pragma include ("UNIX_HostedStoragePoolView20R.mof")
#pragma include ("UNIX_ContainerView20R.mof")
#pragma include ("UNIX_ViewOnSystem20R.mof")
#pragma include ("UNIX_SystemDeviceView20R.mof")
#pragma include ("UNIX_ConcreteComponentView20R.mof")
#pragma include ("CIM_AbstractElementStatisticalData20R.mof")
#pragma include ("UNIX_ElementStatisticalData20R.mof")
#pragma include ("UNIX_AssociatedAppSystemOverviewStatistics20R.mof")
#pragma include ("UNIX_ElementStatisticalDataView20R.mof")
#pragma include ("CIM_LogicalIdentity20R.mof")
#pragma include ("UNIX_EndpointIdentity20R.mof")
#pragma include ("UNIX_NetworkVirtualAdapter20R.mof")
#pragma include ("UNIX_ConcreteIdentity20R.mof")
#pragma include ("UNIX_AttachedElement20R.mof")
#pragma include ("UNIX_MountedElement20R.mof")
#pragma include ("UNIX_ImportedShare20R.mof")
#pragma include ("CIM_SWRManageableAspect20R.mof")
#pragma include ("UNIX_SWRFileAspect20R.mof")
#pragma include ("UNIX_SWRDatabaseAspect20R.mof")
#pragma include ("UNIX_SWRPEPAspect20R.mof")
#pragma include ("UNIX_AccountIdentity20R.mof")
#pragma include ("UNIX_DeviceIdentity20R.mof")
#pragma include ("UNIX_FileIdentity20R.mof")
#pragma include ("UNIX_SharedElement20R.mof")
#pragma include ("CIM_ElementSettingData20R.mof")
#pragma include ("UNIX_TransformOfSecurityAssociation20R.mof")
#pragma include ("UNIX_FileShareSettingData20R.mof")
#pragma include ("UNIX_StorageHardwareIDElementSettingData20R.mof")
#pragma include ("UNIX_ComputerSystemElementSettingData20R.mof")
#pragma include ("CIM_Statistics20R.mof")
#pragma include ("UNIX_ServiceStatistics20R.mof")
#pragma include ("UNIX_BGPServiceStatistics20R.mof")
#pragma include ("UNIX_ErrorCountersForDevice20R.mof")
#pragma include ("UNIX_DeviceStatistics20R.mof")
#pragma include ("UNIX_PhysicalStatistics20R.mof")
#pragma include ("UNIX_ProcessStatistics20R.mof")
#pragma include ("UNIX_SystemStatistics20R.mof")
#pragma include ("UNIX_SAPStatistics20R.mof")
#pragma include ("CIM_MemberOfCollection20R.mof")
#pragma include ("UNIX_EndpointInLink20R.mof")
#pragma include ("UNIX_ElementInPolicyRoleCollection20R.mof")
#pragma include ("UNIX_OrgEntityAssignedVLAN20R.mof")
#pragma include ("UNIX_CollectedBufferPool20R.mof")
#pragma include ("UNIX_MemberPrincipal20R.mof")
#pragma include ("UNIX_MemberOfPolicyCollection20R.mof")
#pragma include ("UNIX_MemberOfStatusCollection20R.mof")
#pragma include ("CIM_CollectedMSEs20R.mof")
#pragma include ("UNIX_DriveInDiskGroup20R.mof")
#pragma include ("UNIX_BGPPeerUsesRouteMap20R.mof")
#pragma include ("UNIX_RoutersInBGPCluster20R.mof")
#pragma include ("UNIX_InBGPPeerGroup20R.mof")
#pragma include ("UNIX_ExtentInDiskGroup20R.mof")
#pragma include ("UNIX_InLogicalNetwork20R.mof")
#pragma include ("UNIX_InSegment20R.mof")
#pragma include ("UNIX_PolicySetInRoleCollection20R.mof")
#pragma include ("UNIX_OrderedMemberOfCollection20R.mof")
#pragma include ("UNIX_CollectedSoftwareElements20R.mof")
#pragma include ("UNIX_CollectedSoftwareFeatures20R.mof")
#pragma include ("CIM_Dependency20R.mof")
#pragma include ("CIM_SettingAssociatedToCapabilities20R.mof")
#pragma include ("UNIX_StorageSettingsGeneratedFromCapabilities20R.mof")
#pragma include ("UNIX_StorageSettingsAssociatedToCapabilities20R.mof")
#pragma include ("UNIX_ScopedView20R.mof")
#pragma include ("UNIX_ResourcePoolExtentDependency20R.mof")
#pragma include ("UNIX_InstalledPartitionTable20R.mof")
#pragma include ("UNIX_SnapshotOfVirtualSystem20R.mof")
#pragma include ("UNIX_ElementAsUser20R.mof")
#pragma include ("CIM_ManagedCredential20R.mof")
#pragma include ("UNIX_SharedSecretIsShared20R.mof")
#pragma include ("UNIX_LocallyManagedPublicKey20R.mof")
#pragma include ("UNIX_KDCIssuesKerberosTicket20R.mof")
#pragma include ("UNIX_IKESecretIsNamed20R.mof")
#pragma include ("UNIX_CASignsPublicKeyCertificate20R.mof")
#pragma include ("UNIX_RouteUsesEndpoint20R.mof")
#pragma include ("UNIX_QueueForPrintService20R.mof")
#pragma include ("UNIX_DoorAccessToPhysicalElement20R.mof")
#pragma include ("UNIX_AllocatedResource20R.mof")
#pragma include ("UNIX_AllocatedDMA20R.mof")
#pragma include ("UNIX_CalculatedRoutes20R.mof")
#pragma include ("UNIX_AdapterActiveConnection20R.mof")
#pragma include ("UNIX_PeerOfSAEndpoint20R.mof")
#pragma include ("CIM_AbstractProtocolControllerForDevice20R.mof")
#pragma include ("CIM_ProtocolControllerForDevice20R.mof")
#pragma include ("UNIX_ProtocolControllerAccessesUnit20R.mof")
#pragma include ("UNIX_AssociatedProtocolController20R.mof")
#pragma include ("UNIX_ProtocolControllerForUnit20R.mof")
#pragma include ("UNIX_ProtocolControllerForPort20R.mof")
#pragma include ("UNIX_ProtocolControllerForUnitView20R.mof")
#pragma include ("UNIX_HeadTailDropQueueBinding20R.mof")
#pragma include ("UNIX_FilterOfPacketCondition20R.mof")
#pragma include ("UNIX_MetricForME20R.mof")
#pragma include ("UNIX_Phase1SAUsedForPhase220R.mof")
#pragma include ("UNIX_TransparentBridgingStaticForwarding20R.mof")
#pragma include ("UNIX_PrinterServicingJob20R.mof")
#pragma include ("UNIX_AssociatedDatabaseSystem20R.mof")
#pragma include ("UNIX_BGPAdminDistance20R.mof")
#pragma include ("UNIX_AssociatedPrintInterpreter20R.mof")
#pragma include ("UNIX_OSPFServiceConfiguration20R.mof")
#pragma include ("CIM_AssociatedMaskingGroup20R.mof")
#pragma include ("UNIX_AssociatedTargetMaskingGroup20R.mof")
#pragma include ("UNIX_AssociatedDeviceMaskingGroup20R.mof")
#pragma include ("UNIX_AssociatedInitiatorMaskingGroup20R.mof")
#pragma include ("CIM_PackageDependency20R.mof")
#pragma include ("UNIX_PackageTempSensor20R.mof")
#pragma include ("UNIX_PackageAlarm20R.mof")
#pragma include ("UNIX_PackageCooling20R.mof")
#pragma include ("UNIX_MoreRoleInfo20R.mof")
#pragma include ("CIM_Realizes20R.mof")
#pragma include ("CIM_RealizesExtent20R.mof")
#pragma include ("UNIX_RealizesDiskPartition20R.mof")
#pragma include ("UNIX_RealizedOnSide20R.mof")
#pragma include ("UNIX_RealizesPExtent20R.mof")
#pragma include ("UNIX_RealizesTapePartition20R.mof")
#pragma include ("UNIX_RealizesAggregatePExtent20R.mof")
#pragma include ("UNIX_RealizesProcessor20R.mof")
#pragma include ("UNIX_SqlObjectForDatabase20R.mof")
#pragma include ("UNIX_ConcreteDependency20R.mof")
#pragma include ("UNIX_StorageHardwareIDManagementServiceDependency20R.mof")
#pragma include ("UNIX_MoreGroupInfo20R.mof")
#pragma include ("UNIX_SettingsAffectSettings20R.mof")
#pragma include ("CIM_SAPSAPDependency20R.mof")
#pragma include ("CIM_ActiveConnection20R.mof")
#pragma include ("UNIX_LinkAggregatorPartnerConnection20R.mof")
#pragma include ("UNIX_FCActiveConnection20R.mof")
#pragma include ("UNIX_LAGPortPartnerConnection20R.mof")
#pragma include ("UNIX_BindsTo20R.mof")
#pragma include ("UNIX_BindsToLANEndpoint20R.mof")
#pragma include ("UNIX_Switchable20R.mof")
#pragma include ("UNIX_SwitchPortPair20R.mof")
#pragma include ("UNIX_InboundVLAN20R.mof")
#pragma include ("UNIX_OutboundVLAN20R.mof")
#pragma include ("UNIX_EndpointForIPNetworkConnection20R.mof")
#pragma include ("UNIX_HomeForMedia20R.mof")
#pragma include ("UNIX_ExecutionRequirement20R.mof")
#pragma include ("UNIX_RecoveryJob20R.mof")
#pragma include ("UNIX_AddressesToBeTranslated20R.mof")
#pragma include ("UNIX_BIOSLoadedInNV20R.mof")
#pragma include ("UNIX_EndpointOfNetworkPipe20R.mof")
#pragma include ("UNIX_BGPAttributesForRoute20R.mof")
#pragma include ("UNIX_QueueForwardsToPrintSAP20R.mof")
#pragma include ("UNIX_LibraryExchange20R.mof")
#pragma include ("UNIX_DoorAccessToDevice20R.mof")
#pragma include ("UNIX_ReferencedSpecification20R.mof")
#pragma include ("UNIX_ReferencedProfile20R.mof")
#pragma include ("UNIX_SubProfileRequiresProfile20R.mof")
#pragma include ("UNIX_RequireCredentialsFrom20R.mof")
#pragma include ("UNIX_LogInDeviceFile20R.mof")
#pragma include ("UNIX_SystemAdministratorGroup20R.mof")
#pragma include ("UNIX_DiscreteMetricValueDependency20R.mof")
#pragma include ("UNIX_ReflectorNonClientService20R.mof")
#pragma include ("UNIX_CommMechanismForAdapter20R.mof")
#pragma include ("UNIX_ManagesAccount20R.mof")
#pragma include ("UNIX_AuthenticateForUse20R.mof")
#pragma include ("UNIX_UsersCredential20R.mof")
#pragma include ("UNIX_PublicPrivateKeyPair20R.mof")
#pragma include ("UNIX_AssociatedAlarm20R.mof")
#pragma include ("UNIX_TrustHierarchy20R.mof")
#pragma include ("CIM_ProvidesServiceToElement20R.mof")
#pragma include ("UNIX_SecurityServiceForSystem20R.mof")
#pragma include ("UNIX_ManagesAccountOnSystem20R.mof")
#pragma include ("CIM_ServiceServiceDependency20R.mof")
#pragma include ("UNIX_SchedulerUsed20R.mof")
#pragma include ("UNIX_CalculationServiceForDropper20R.mof")
#pragma include ("UNIX_EGPRouteCalcDependency20R.mof")
#pragma include ("UNIX_ServiceUsesSecurityService20R.mof")
#pragma include ("UNIX_QueueHierarchy20R.mof")
#pragma include ("UNIX_RelatedSpanningTree20R.mof")
#pragma include ("UNIX_CalculationBasedOnQueue20R.mof")
#pragma include ("UNIX_DiagnosticTestForMSE20R.mof")
#pragma include ("UNIX_SchemaCharacterSet20R.mof")
#pragma include ("UNIX_AuthorizationSubject20R.mof")
#pragma include ("UNIX_MPLSFecOfTunnel20R.mof")
#pragma include ("UNIX_ClassifierElementUsesFilterList20R.mof")
#pragma include ("UNIX_NotaryVerifiesBiometric20R.mof")
#pragma include ("UNIX_PrinterServicingQueue20R.mof")
#pragma include ("UNIX_ClassifierFilterSet20R.mof")
#pragma include ("UNIX_SharedElementRoot20R.mof")
#pragma include ("UNIX_MPLSCurrentlyAssignedLSP20R.mof")
#pragma include ("UNIX_MPLSBackupLSP20R.mof")
#pragma include ("UNIX_StorageProcessorAffinity20R.mof")
#pragma include ("UNIX_IPsecPolicyForEndpoint20R.mof")
#pragma include ("UNIX_MostCurrentSnapshotInBranch20R.mof")
#pragma include ("UNIX_MorePersonInfo20R.mof")
#pragma include ("UNIX_ConnectedTo20R.mof")
#pragma include ("UNIX_SlotInSlot20R.mof")
#pragma include ("UNIX_ReflectorService20R.mof")
#pragma include ("CIM_ServiceAccessBySAP20R.mof")
#pragma include ("UNIX_ClusterServiceAccessBySAP20R.mof")
#pragma include ("UNIX_CommMechanismForManager20R.mof")
#pragma include ("UNIX_BootServiceAccessBySAP20R.mof")
#pragma include ("UNIX_ProvidesEndpoint20R.mof")
#pragma include ("UNIX_LastAppliedSnapshot20R.mof")
#pragma include ("UNIX_ApplicationSystemDependency20R.mof")
#pragma include ("UNIX_UseOfLog20R.mof")
#pragma include ("UNIX_UseOfMessageLog20R.mof")
#pragma include ("UNIX_OperationLog20R.mof")
#pragma include ("CIM_DeviceServiceImplementation20R.mof")
#pragma include ("UNIX_WakeUpServiceOnNetworkPort20R.mof")
#pragma include ("UNIX_OOBAlertServiceOnNetworkPort20R.mof")
#pragma include ("UNIX_OOBAlertServiceOnNetworkAdapter20R.mof")
#pragma include ("UNIX_OOBAlertServiceOnModem20R.mof")
#pragma include ("UNIX_WakeUpServiceOnNetworkAdapter20R.mof")
#pragma include ("UNIX_WakeUpServiceOnModem20R.mof")
#pragma include ("UNIX_ExecutionTarget20R.mof")
#pragma include ("UNIX_AssociatedNextHop20R.mof")
#pragma include ("UNIX_LogInDataFile20R.mof")
#pragma include ("UNIX_DeviceSoftware20R.mof")
#pragma include ("UNIX_RemoteAccessAvailableToElement20R.mof")
#pragma include ("UNIX_AssociatedCooling20R.mof")
#pragma include ("UNIX_AcceptCredentialFrom20R.mof")
#pragma include ("UNIX_AggregatedVirtualSystemManagementService20R.mof")
#pragma include ("UNIX_FilterOfSecurityAssociation20R.mof")
#pragma include ("UNIX_RelatedElementCausingError20R.mof")
#pragma include ("UNIX_MemoryWithMedia20R.mof")
#pragma include ("UNIX_ElementView20R.mof")
#pragma include ("UNIX_IdentificationOfManagedSystem20R.mof")
#pragma include ("UNIX_DiagnosticTestSoftware20R.mof")
#pragma include ("UNIX_AssociatedIndicatorLED20R.mof")
#pragma include ("CIM_DeviceConnection20R.mof")
#pragma include ("UNIX_USBConnection20R.mof")
#pragma include ("CIM_ControlledBy20R.mof")
#pragma include ("UNIX_USBControllerHasHub20R.mof")
#pragma include ("UNIX_SerialInterface20R.mof")
#pragma include ("UNIX_SCSIInterface20R.mof")
#pragma include ("UNIX_MPLSCrossConnectLSP20R.mof")
#pragma include ("UNIX_PortActiveConnection20R.mof")
#pragma include ("UNIX_AssociatedResourcePool20R.mof")
#pragma include ("UNIX_AuthorizedUse20R.mof")
#pragma include ("UNIX_Spared20R.mof")
#pragma include ("UNIX_PeerGatewayForTunnel20R.mof")
#pragma include ("UNIX_BGPPeerGroupService20R.mof")
#pragma include ("UNIX_SoftwareElementSAPImplementation20R.mof")
#pragma include ("UNIX_PeerGatewayForPreconfiguredTunnel20R.mof")
#pragma include ("UNIX_SwitchPortStaticForwarding20R.mof")
#pragma include ("UNIX_AuthorizationTarget20R.mof")
#pragma include ("UNIX_CommMechanismForObjectManagerAdapter20R.mof")
#pragma include ("UNIX_IsSpare20R.mof")
#pragma include ("UNIX_ResidesOnExtent20R.mof")
#pragma include ("UNIX_MPLSEndpointBuffers20R.mof")
#pragma include ("UNIX_AssociatedBattery20R.mof")
#pragma include ("UNIX_SystemAdministrator20R.mof")
#pragma include ("UNIX_RecordAppliesToElement20R.mof")
#pragma include ("UNIX_BootOSFromFS20R.mof")
#pragma include ("UNIX_MoreOrganizationInfo20R.mof")
#pragma include ("UNIX_TransformOfPreconfiguredAction20R.mof")
#pragma include ("UNIX_MetricDefForME20R.mof")
#pragma include ("UNIX_QueueAllocation20R.mof")
#pragma include ("UNIX_MPLSNextHopInTunnel20R.mof")
#pragma include ("UNIX_BGPRoutingPolicy20R.mof")
#pragma include ("UNIX_ConditioningServiceOnEndpoint20R.mof")
#pragma include ("UNIX_RunningOS20R.mof")
#pragma include ("UNIX_SnapshotOfExtent20R.mof")
#pragma include ("UNIX_ElementInConnector20R.mof")
#pragma include ("UNIX_PackageInConnector20R.mof")
#pragma include ("UNIX_PackageInSlot20R.mof")
#pragma include ("UNIX_CardInSlot20R.mof")
#pragma include ("CIM_AssociatedSensor20R.mof")
#pragma include ("UNIX_AssociatedSupplyVoltageSensor20R.mof")
#pragma include ("UNIX_AssociatedSupplyCurrentSensor20R.mof")
#pragma include ("CIM_AssociatedLabelReader20R.mof")
#pragma include ("UNIX_AccessLabelReader20R.mof")
#pragma include ("UNIX_ReplicaPoolForStorage20R.mof")
#pragma include ("UNIX_DiscreteMetricDefinitionDependency20R.mof")
#pragma include ("UNIX_ResourceAllocationFromPool20R.mof")
#pragma include ("UNIX_RoutesBGP20R.mof")
#pragma include ("UNIX_AccountMapsToAccount20R.mof")
#pragma include ("UNIX_MPLSReverseDirectionTunnel20R.mof")
#pragma include ("UNIX_Docked20R.mof")
#pragma include ("UNIX_MoreOrgUnitInfo20R.mof")
#pragma include ("UNIX_SystemAdministratorRole20R.mof")
#pragma include ("UNIX_MetricInstance20R.mof")
#pragma include ("UNIX_LogInStorage20R.mof")
#pragma include ("UNIX_TranslationPoolForNAT20R.mof")
#pragma include ("UNIX_PhysicalMediaInLocation20R.mof")
#pragma include ("UNIX_ElementsLinked20R.mof")
#pragma include ("UNIX_AreaOfConfiguration20R.mof")
#pragma include ("UNIX_ElementSoftwareIdentity20R.mof")
#pragma include ("UNIX_SoftwareFeatureServiceImplementation20R.mof")
#pragma include ("CIM_AbstractElementAllocatedFromPool20R.mof")
#pragma include ("UNIX_AllocatedFromStoragePoolViewView20R.mof")
#pragma include ("UNIX_AllocatedFromStoragePoolView20R.mof")
#pragma include ("UNIX_ElementAllocatedFromPool20R.mof")
#pragma include ("UNIX_AllocatedFromStoragePool20R.mof")
#pragma include ("CIM_ServiceSAPDependency20R.mof")
#pragma include ("UNIX_CalculatesAmong20R.mof")
#pragma include ("UNIX_EgressConditioningServiceOnEndpoint20R.mof")
#pragma include ("CIM_ForwardsAmong20R.mof")
#pragma include ("UNIX_SwitchesAmong20R.mof")
#pragma include ("UNIX_NATServiceRunningOnEndpoint20R.mof")
#pragma include ("UNIX_SwitchPortSpanningTree20R.mof")
#pragma include ("UNIX_IngressConditioningServiceOnEndpoint20R.mof")
#pragma include ("UNIX_RelatedTransparentBridgingService20R.mof")
#pragma include ("UNIX_SwitchPortSourceRouting20R.mof")
#pragma include ("UNIX_VLANFor20R.mof")
#pragma include ("UNIX_DeviceSAPImplementation20R.mof")
#pragma include ("UNIX_PortImplementsEndpoint20R.mof")
#pragma include ("UNIX_Mount20R.mof")
#pragma include ("UNIX_SoftwareElementServiceImplementation20R.mof")
#pragma include ("UNIX_AuthenticationTarget20R.mof")
#pragma include ("UNIX_ExecutionCandidate20R.mof")
#pragma include ("UNIX_RangesOfConfiguration20R.mof")
#pragma include ("UNIX_VRFRoute20R.mof")
#pragma include ("UNIX_RouteForwardedByService20R.mof")
#pragma include ("UNIX_ForwardedRoutes20R.mof")
#pragma include ("UNIX_AsymmetricAccessibility20R.mof")
#pragma include ("UNIX_DeviceServicesLocation20R.mof")
#pragma include ("UNIX_MPLSSegmentOnProtocolEP20R.mof")
#pragma include ("CIM_SystemPackaging20R.mof")
#pragma include ("UNIX_LibraryPackage20R.mof")
#pragma include ("UNIX_ComputerSystemPackage20R.mof")
#pragma include ("UNIX_SwitchPortDynamicForwarding20R.mof")
#pragma include ("UNIX_DatabaseAdministrator20R.mof")
#pragma include ("UNIX_AssociatedPrintSupply20R.mof")
#pragma include ("UNIX_SecurityServiceUsesAccount20R.mof")
#pragma include ("CIM_AbstractBasedOn20R.mof")
#pragma include ("UNIX_BasedOnView20R.mof")
#pragma include ("CIM_BasedOn20R.mof")
#pragma include ("UNIX_CompositeExtentBasedOn20R.mof")
#pragma include ("UNIX_DiskPartitionBasedOnVolume20R.mof")
#pragma include ("UNIX_ProtectedExtentBasedOn20R.mof")
#pragma include ("UNIX_PSExtentBasedOnPExtent20R.mof")
#pragma include ("UNIX_TapePartitionOnSurface20R.mof")
#pragma include ("CIM_LogicalDiskBasedOnExtent20R.mof")
#pragma include ("UNIX_LogicalDiskBasedOnPartition20R.mof")
#pragma include ("UNIX_LogicalDiskBasedOnVolume20R.mof")
#pragma include ("UNIX_LogicalDiskBasedOnVolumeSet20R.mof")
#pragma include ("UNIX_AggregatePSExtentBasedOnPExtent20R.mof")
#pragma include ("UNIX_AggregatePSExtentBasedOnAggregatePExtent20R.mof")
#pragma include ("UNIX_VolumeSetBasedOnPSExtent20R.mof")
#pragma include ("UNIX_SoftwareFeatureSAPImplementation20R.mof")
#pragma include ("UNIX_QueueForBatchService20R.mof")
#pragma include ("UNIX_OrderedDependency20R.mof")
#pragma include ("CIM_AssociatedMemory20R.mof")
#pragma include ("UNIX_AssociatedProcessorMemory20R.mof")
#pragma include ("UNIX_AssociatedCacheMemory20R.mof")
#pragma include ("UNIX_MPLSSegmentInXC20R.mof")
#pragma include ("UNIX_StorageElementDriveDependency20R.mof")
#pragma include ("UNIX_MediaPresent20R.mof")
#pragma include ("UNIX_RuleThatGeneratedSA20R.mof")
#pragma include ("UNIX_ProcessExecutable20R.mof")
#pragma include ("UNIX_ResourcePoolDriveDependency20R.mof")
#pragma include ("UNIX_UsersAccount20R.mof")
#pragma include ("UNIX_TransparentBridgingDynamicForwarding20R.mof")
#pragma include ("UNIX_RelatedTopologyGraph20R.mof")
#pragma include ("UNIX_AssociatedTierPolicy20R.mof")
#pragma include ("UNIX_DeviceAccessedByFile20R.mof")
#pragma include ("UNIX_FilterListsInBGPRouteMap20R.mof")
#pragma include ("CIM_HostedDependency20R.mof")
#pragma include ("UNIX_HostedFilterList20R.mof")
#pragma include ("UNIX_HostedMPLSTunnelHop20R.mof")
#pragma include ("UNIX_HostedAuthenticationRequirement20R.mof")
#pragma include ("UNIX_HostedShare20R.mof")
#pragma include ("UNIX_HostedRoute20R.mof")
#pragma include ("UNIX_HostedBGPAttributes20R.mof")
#pragma include ("UNIX_NetworkServicesInAdminDomain20R.mof")
#pragma include ("UNIX_VideoHeadOnController20R.mof")
#pragma include ("UNIX_ScopedSetting20R.mof")
#pragma include ("UNIX_ConfigurationForSystem20R.mof")
#pragma include ("UNIX_HostedBGPPeerGroup20R.mof")
#pragma include ("UNIX_HostingCS20R.mof")
#pragma include ("CIM_PortOnDevice20R.mof")
#pragma include ("UNIX_USBPortOnHub20R.mof")
#pragma include ("UNIX_FibrePortOnFCAdapter20R.mof")
#pragma include ("CIM_HostedService20R.mof")
#pragma include ("UNIX_HostedRoutingServices20R.mof")
#pragma include ("UNIX_HostedBootService20R.mof")
#pragma include ("UNIX_HostedClusterService20R.mof")
#pragma include ("UNIX_HostedForwardingServices20R.mof")
#pragma include ("UNIX_HostedNetworkPipe20R.mof")
#pragma include ("UNIX_HostedACI20R.mof")
#pragma include ("UNIX_HostedAdminDistance20R.mof")
#pragma include ("UNIX_SettingForSystem20R.mof")
#pragma include ("UNIX_DatabaseControlFile20R.mof")
#pragma include ("UNIX_HostedRoutingPolicy20R.mof")
#pragma include ("UNIX_SharingDependency20R.mof")
#pragma include ("UNIX_HostedBGPRouteMap20R.mof")
#pragma include ("UNIX_HostedCollection20R.mof")
#pragma include ("UNIX_PolicyRoleCollectionInSystem20R.mof")
#pragma include ("UNIX_NamespaceInManager20R.mof")
#pragma include ("CIM_HostedAccessPoint20R.mof")
#pragma include ("UNIX_HostedIPInterface20R.mof")
#pragma include ("UNIX_HostedClusterSAP20R.mof")
#pragma include ("UNIX_HostedBootSAP20R.mof")
#pragma include ("CIM_PolicyInSystem20R.mof")
#pragma include ("UNIX_ReusablePolicy20R.mof")
#pragma include ("UNIX_PolicyActionInPolicyRepository20R.mof")
#pragma include ("UNIX_PolicyConditionInPolicyRepository20R.mof")
#pragma include ("CIM_PolicySetInSystem20R.mof")
#pragma include ("UNIX_PolicyRuleInSystem20R.mof")
#pragma include ("UNIX_PolicyGroupInSystem20R.mof")
#pragma include ("UNIX_HostedJobDestination20R.mof")
#pragma include ("UNIX_HostedFilterEntryBase20R.mof")
#pragma include ("UNIX_ResourceDependentOnResource20R.mof")
#pragma include ("UNIX_IPsecPolicyForSystem20R.mof")
#pragma include ("UNIX_CAHasPublicCertificate20R.mof")
#pragma include ("UNIX_ParticipatingCS20R.mof")
#pragma include ("UNIX_MPLSFilterAtXC20R.mof")
#pragma include ("UNIX_SuppliesPower20R.mof")
#pragma include ("UNIX_ImportedShareRoot20R.mof")
#pragma include ("UNIX_MPLSHopInTunnel20R.mof")
#pragma include ("UNIX_ReflectorClientService20R.mof")
#pragma include ("UNIX_JobDestinationJobs20R.mof")
#pragma include ("UNIX_OwningPrintQueue20R.mof")
#pragma include ("UNIX_CollectionInSystem20R.mof")
#pragma include ("UNIX_ReplaceableProductFRU20R.mof")
#pragma include ("UNIX_ElementCapabilities20R.mof")
#pragma include ("UNIX_ServiceOptionAspect20R.mof")
#pragma include ("UNIX_ElementProfile20R.mof")
#pragma include ("UNIX_AuthorizedTarget20R.mof")
#pragma include ("UNIX_ProductFRU20R.mof")
#pragma include ("UNIX_LogOfIndication20R.mof")
#pragma include ("UNIX_FromDirectorySpecification20R.mof")
#pragma include ("UNIX_RecordInLog20R.mof")
#pragma include ("UNIX_DefaultElementCapabilities20R.mof")
#pragma include ("UNIX_CollectionSetting20R.mof")
#pragma include ("UNIX_ElementCapacity20R.mof")
#pragma include ("UNIX_CollectionConfiguration20R.mof")
#pragma include ("UNIX_SystemInNamespace20R.mof")
#pragma include ("UNIX_ProductSoftwareFeatures20R.mof")
#pragma include ("UNIX_ProductParentChild20R.mof")
#pragma include ("UNIX_StorageDefect20R.mof")
#pragma include ("UNIX_CollectionInOrganization20R.mof")
#pragma include ("UNIX_ServiceAffectsElement20R.mof")
#pragma include ("UNIX_FRUIncludesProduct20R.mof")
#pragma include ("UNIX_OwningCollectionElement20R.mof")
#pragma include ("UNIX_ElementLocation20R.mof")
#pragma include ("UNIX_SystemSettingContext20R.mof")
#pragma include ("UNIX_ServiceAvailableToElement20R.mof")
#pragma include ("UNIX_ActionSequence20R.mof")
#pragma include ("UNIX_DiagnosticResultForTest20R.mof")
#pragma include ("UNIX_DiagnosticResultForMSE20R.mof")
#pragma include ("UNIX_CompatibleProduct20R.mof")
#pragma include ("UNIX_InstalledSoftwareIdentity20R.mof")
#pragma include ("UNIX_FRUIncludesSoftwareFeature20R.mof")
#pragma include ("UNIX_MaskingMappingExposedDeviceView20R.mof")
#pragma include ("UNIX_SchemaInformationStructure20R.mof")
#pragma include ("UNIX_InstalledSoftwareElement20R.mof")
#pragma include ("UNIX_FibrePortActiveLogin20R.mof")
#pragma include ("UNIX_CollectedCollections20R.mof")
#pragma include ("UNIX_CorrespondingSettingDataRecord20R.mof")
#pragma include ("UNIX_ElementConfiguration20R.mof")
#pragma include ("UNIX_AffectedJobElement20R.mof")
#pragma include ("UNIX_ComponentSetting20R.mof")
#pragma include ("UNIX_NetworksInAdminDomain20R.mof")
#pragma include ("UNIX_OwningJobElement20R.mof")
#pragma include ("UNIX_ToDirectoryAction20R.mof")
#pragma include ("UNIX_SAPAvailableForElement20R.mof")
#pragma include ("UNIX_DiagnosticResultInPackage20R.mof")
#pragma include ("UNIX_RelatedStatistics20R.mof")
#pragma include ("UNIX_BGPClustersInAS20R.mof")
#pragma include ("UNIX_AssociatedFileSystemStatisticsManifestCollection20R.mof")
#pragma include ("UNIX_Message20R.mof")
#pragma include ("UNIX_CredentialContext20R.mof")
#pragma include ("UNIX_FromDirectoryAction20R.mof")
#pragma include ("UNIX_AFRelatedServices20R.mof")
#pragma include ("UNIX_RoleLimitedToTarget20R.mof")
#pragma include ("UNIX_ActsAsSpare20R.mof")
#pragma include ("UNIX_OrgStructure20R.mof")
#pragma include ("UNIX_AssociatedJobMethodResult20R.mof")
#pragma include ("UNIX_SettingContext20R.mof")
#pragma include ("UNIX_FRUPhysicalElements20R.mof")
#pragma include ("UNIX_NextService20R.mof")
#pragma include ("UNIX_LogicalNetworkService20R.mof")
#pragma include ("UNIX_ElementSetting20R.mof")
#pragma include ("UNIX_DependencyContext20R.mof")
#pragma include ("UNIX_ProductSupport20R.mof")
#pragma include ("UNIX_GenericOperationCapabilitiesStructure20R.mof")
#pragma include ("UNIX_RelatedStatisticalData20R.mof")
#pragma include ("UNIX_ElementSecuritySensitivity20R.mof")
#pragma include ("UNIX_AssignedIdentity20R.mof")
#pragma include ("UNIX_Synchronized20R.mof")
#pragma include ("UNIX_CorrespondingSettingsRecord20R.mof")
#pragma include ("UNIX_LogManagesRecord20R.mof")
#pragma include ("UNIX_ElementHasBeenFRUed20R.mof")
#pragma include ("UNIX_ServiceProcess20R.mof")
#pragma include ("UNIX_NextServiceAfterMeter20R.mof")
#pragma include ("UNIX_QueueToSchedule20R.mof")
#pragma include ("UNIX_ApplicationSystemDirectory20R.mof")
#pragma include ("UNIX_PolicySetAppliesToElement20R.mof")
#pragma include ("UNIX_ParameterValueSources20R.mof")
#pragma include ("UNIX_DirectorySpecificationFile20R.mof")
#pragma include ("UNIX_AssociatedPrivilege20R.mof")
#pragma include ("UNIX_ParametersForMethod20R.mof")
#pragma include ("UNIX_Export20R.mof")
#pragma include ("UNIX_ElementConformsToProfile20R.mof")
#pragma include ("UNIX_AdjacentSlots20R.mof")
#pragma include ("UNIX_ProductPhysicalElements20R.mof")
#pragma include ("UNIX_IdentityContext20R.mof")
#pragma include ("UNIX_ElementFRU20R.mof")
#pragma include ("UNIX_InstalledProductImage20R.mof")
#pragma include ("UNIX_ToDirectorySpecification20R.mof")
#pragma include ("UNIX_InitiatorTargetLogicalUnitPath20R.mof")
#pragma include ("UNIX_ProductProductDependency20R.mof")
#pragma include ("UNIX_DiagnosticResult20R.mof")
#pragma include ("UNIX_SchedulingServiceToSchedule20R.mof")
#pragma include ("UNIX_AuthorizedSubject20R.mof")
#pragma include ("UNIX_SettingsDefineState20R.mof")
#pragma include ("UNIX_SoftwareElementActions20R.mof")
#pragma include ("UNIX_SoftwareElementChecks20R.mof")
#pragma include ("UNIX_AssociatedBlockStatisticsManifestCollection20R.mof")
#pragma include ("UNIX_ParticipatesInSet20R.mof")
#pragma include ("UNIX_ServiceOption20R.mof")
#pragma include ("UNIX_MaskingMappingView20R.mof")
#pragma include ("UNIX_ConfigurationComponent20R.mof")

