#//%LICENSE////////////////////////////////////////////////////////////////
#//
#// Licensed to The Open Group (TOG) under one or more contributor license
#// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
#// this work for additional information regarding copyright ownership.
#// Each contributor licenses this file to you under the OpenPegasus Open
#// Source License; you may not use this file except in compliance with the
#// License.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a
#// copy of this software and associated documentation files (the "Software"),
#// to deal in the Software without restriction, including without limitation
#// the rights to use, copy, modify, merge, publish, distribute, sublicense,
#// and/or sell copies of the Software, and to permit persons to whom the
#// Software is furnished to do so, subject to the following conditions:
#//
#// The above copyright notice and this permission notice shall be included
#// in all copies or substantial portions of the Software.
#//
#// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//////////////////////////////////////////////////////////////////////////
#//
#//%/////////////////////////////////////////////////////////////////////////


ROOT = ../../../..
DIRS = \
	$(ROOT)/src/Providers/UNIXProviders/AlarmDevice \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIArbitraryLogicalUnit \
\
	$(ROOT)/src/Providers/UNIXProviders/Button \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerSupply \
\
	$(ROOT)/src/Providers/UNIXProviders/UninterruptiblePowerSupply \
\
	$(ROOT)/src/Providers/UNIXProviders/Battery \
\
	$(ROOT)/src/Providers/UNIXProviders/TapeDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/CDROMDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/WORMDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/DVDDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/DisketteDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/MagnetoOpticalDrive \
\
	$(ROOT)/src/Providers/UNIXProviders/USBDevice \
\
	$(ROOT)/src/Providers/UNIXProviders/USBHub \
\
	$(ROOT)/src/Providers/UNIXProviders/PowerConnectionPoint \
\
	$(ROOT)/src/Providers/UNIXProviders/LabelReader \
\
	$(ROOT)/src/Providers/UNIXProviders/LogicalDisk \
\
	$(ROOT)/src/Providers/UNIXProviders/Snapshot \
\
	$(ROOT)/src/Providers/UNIXProviders/VTOCDiskPartition \
\
	$(ROOT)/src/Providers/UNIXProviders/GPTDiskPartition \
\
	$(ROOT)/src/Providers/UNIXProviders/DiskPartition \
\
	$(ROOT)/src/Providers/UNIXProviders/TapePartition \
\
	$(ROOT)/src/Providers/UNIXProviders/CompositeExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtectedSpaceExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/PhysicalExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/DatabaseSegment \
\
	$(ROOT)/src/Providers/UNIXProviders/AggregatePExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/VolumeSet \
\
	$(ROOT)/src/Providers/UNIXProviders/OpaqueManagementData \
\
	$(ROOT)/src/Providers/UNIXProviders/AggregatePSExtent \
\
	$(ROOT)/src/Providers/UNIXProviders/CacheMemory \
\
	$(ROOT)/src/Providers/UNIXProviders/VolatileStorage \
\
	$(ROOT)/src/Providers/UNIXProviders/NonVolatileStorage \
\
	$(ROOT)/src/Providers/UNIXProviders/Printer \
\
	$(ROOT)/src/Providers/UNIXProviders/CurrentSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/TemperatureSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/VoltageSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/Tachometer \
\
	$(ROOT)/src/Providers/UNIXProviders/MultiStateSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/BinarySensor \
\
	$(ROOT)/src/Providers/UNIXProviders/DiscreteSensor \
\
	$(ROOT)/src/Providers/UNIXProviders/CableModem \
\
	$(ROOT)/src/Providers/UNIXProviders/ADSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/VDSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/HDSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/SDSLModem \
\
	$(ROOT)/src/Providers/UNIXProviders/Unimodem \
\
	$(ROOT)/src/Providers/UNIXProviders/ISDNModem \
\
	$(ROOT)/src/Providers/UNIXProviders/Keyboard \
\
	$(ROOT)/src/Providers/UNIXProviders/PointingDevice \
\
	$(ROOT)/src/Providers/UNIXProviders/DesktopMonitor \
\
	$(ROOT)/src/Providers/UNIXProviders/FlatPanel \
\
	$(ROOT)/src/Providers/UNIXProviders/Processor \
\
	$(ROOT)/src/Providers/UNIXProviders/VideoHead \
\
	$(ROOT)/src/Providers/UNIXProviders/FingerprintReader \
\
	$(ROOT)/src/Providers/UNIXProviders/Door \
\
	$(ROOT)/src/Providers/UNIXProviders/SmartCard \
\
	$(ROOT)/src/Providers/UNIXProviders/NetworkPort \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiPort \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetPort \
\
	$(ROOT)/src/Providers/UNIXProviders/LLDPEthernetPort \
\
	$(ROOT)/src/Providers/UNIXProviders/DataCenterEthernetPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SASPort \
\
	$(ROOT)/src/Providers/UNIXProviders/IBPort \
\
	$(ROOT)/src/Providers/UNIXProviders/FCPort \
\
	$(ROOT)/src/Providers/UNIXProviders/WirelessPort \
\
	$(ROOT)/src/Providers/UNIXProviders/TokenRingPort \
\
	$(ROOT)/src/Providers/UNIXProviders/DAPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SerialPort \
\
	$(ROOT)/src/Providers/UNIXProviders/ATAPort \
\
	$(ROOT)/src/Providers/UNIXProviders/USBPort \
\
	$(ROOT)/src/Providers/UNIXProviders/PCIPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SPIPort \
\
	$(ROOT)/src/Providers/UNIXProviders/ParallelPort \
\
	$(ROOT)/src/Providers/UNIXProviders/FibrePort \
\
	$(ROOT)/src/Providers/UNIXProviders/Watchdog \
\
	$(ROOT)/src/Providers/UNIXProviders/EthernetAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/TokenRingAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/FibreChannelAdapter \
\
	$(ROOT)/src/Providers/UNIXProviders/IndicatorLED \
\
	$(ROOT)/src/Providers/UNIXProviders/ElectricalSwitch \
\
	$(ROOT)/src/Providers/UNIXProviders/ProtocolController \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIProtocolController \
\
	$(ROOT)/src/Providers/UNIXProviders/WiFiRadio \
\
	$(ROOT)/src/Providers/UNIXProviders/InterLibraryPort \
\
	$(ROOT)/src/Providers/UNIXProviders/LimitedAccessPort \
\
	$(ROOT)/src/Providers/UNIXProviders/SmartCardReader \
\
	$(ROOT)/src/Providers/UNIXProviders/PCIBridge \
\
	$(ROOT)/src/Providers/UNIXProviders/PCIeSwitch \
\
	$(ROOT)/src/Providers/UNIXProviders/PortController \
\
	$(ROOT)/src/Providers/UNIXProviders/IBPortController \
\
	$(ROOT)/src/Providers/UNIXProviders/ParallelController \
\
	$(ROOT)/src/Providers/UNIXProviders/InfraredController \
\
	$(ROOT)/src/Providers/UNIXProviders/ManagementController \
\
	$(ROOT)/src/Providers/UNIXProviders/SSAController \
\
	$(ROOT)/src/Providers/UNIXProviders/AGPVideoController \
\
	$(ROOT)/src/Providers/UNIXProviders/PCVideoController \
\
	$(ROOT)/src/Providers/UNIXProviders/SerialController \
\
	$(ROOT)/src/Providers/UNIXProviders/DisplayController \
\
	$(ROOT)/src/Providers/UNIXProviders/AGPVideoDisplayController \
\
	$(ROOT)/src/Providers/UNIXProviders/USBController \
\
	$(ROOT)/src/Providers/UNIXProviders/IDEController \
\
	$(ROOT)/src/Providers/UNIXProviders/PCMCIAController \
\
	$(ROOT)/src/Providers/UNIXProviders/SCSIController \
\
	$(ROOT)/src/Providers/UNIXProviders/ESCONController \
\
	$(ROOT)/src/Providers/UNIXProviders/DeviceTray \
\
	$(ROOT)/src/Providers/UNIXProviders/PassThroughModule \
\
	$(ROOT)/src/Providers/UNIXProviders/Fan \
\
	$(ROOT)/src/Providers/UNIXProviders/Refrigeration \
\
	$(ROOT)/src/Providers/UNIXProviders/HeatPipe \
\
	$(ROOT)/src/Providers/UNIXProviders/TPM \
\
	$(ROOT)/src/Providers/UNIXProviders/Scanner \




DIR = Providers/UNIXProviders/AssociatedAlarm
include $(ROOT)/mak/config.mak
LIBRARY = UNIX_AssociatedAlarmProvider
EXTRA_INCLUDES += -I/usr/local/include -I./..

DEFINES +=  -DPROVIDER_LIB_NS="UNIX_AssociatedAlarmLib" -DPROVIDER_LIB_NS_BEGIN="namespace UNIX_AssociatedAlarmLib {"

SOURCES = \
	../CIMHelper.cpp \
	UNIX_AssociatedAlarm.cpp \
	UNIX_AssociatedAlarmProvider.cpp \
	UNIX_AssociatedAlarmMain.cpp

ifeq ($(OS), aix)
	SOURCES += UNIX_AssociatedAlarm_AIX.cpp
endif
ifeq ($(OS), darwin)
	SOURCES += UNIX_AssociatedAlarm_DARWIN.cpp
endif
ifeq ($(OS), freebsd)
	SOURCES += UNIX_AssociatedAlarm_FREEBSD.cpp
endif
ifeq ($(OS), hpux)
	SOURCES += UNIX_AssociatedAlarm_HPUX.cpp
endif
ifeq ($(OS), linux)
	SOURCES += UNIX_AssociatedAlarm_LINUX.cpp
endif
ifeq ($(OS), solaris)
	SOURCES += UNIX_AssociatedAlarm_SOLARIS.cpp
endif
ifeq ($(OS), tru64)
	SOURCES += UNIX_AssociatedAlarm_TRU64.cpp
endif
ifeq ($(OS), vms)
	SOURCES += UNIX_AssociatedAlarm_VMS.cpp
endif
ifeq ($(OS), win32)
	SOURCES += UNIX_AssociatedAlarm_WIN32.cpp
endif
ifeq ($(OS), zos)
	SOURCES += UNIX_AssociatedAlarm_ZOS.cpp
endif
ifeq (, $(filter aix,darwin,freebsd,hpux,linux,solaris,tru64,vms,win32,zos $(OS)))

else
	SOURCES += UNIX_AssociatedAlarm_STUB.cpp
endif

LIBRARIES += \
	UNIX_AlarmDeviceProvider\
	UNIX_SCSIArbitraryLogicalUnitProvider\
	UNIX_ButtonProvider\
	UNIX_PowerSupplyProvider\
	UNIX_UninterruptiblePowerSupplyProvider\
	UNIX_BatteryProvider\
	UNIX_TapeDriveProvider\
	UNIX_CDROMDriveProvider\
	UNIX_WORMDriveProvider\
	UNIX_DiskDriveProvider\
	UNIX_DVDDriveProvider\
	UNIX_DisketteDriveProvider\
	UNIX_MagnetoOpticalDriveProvider\
	UNIX_USBDeviceProvider\
	UNIX_USBHubProvider\
	UNIX_PowerConnectionPointProvider\
	UNIX_LabelReaderProvider\
	UNIX_LogicalDiskProvider\
	UNIX_SnapshotProvider\
	UNIX_VTOCDiskPartitionProvider\
	UNIX_GPTDiskPartitionProvider\
	UNIX_DiskPartitionProvider\
	UNIX_TapePartitionProvider\
	UNIX_CompositeExtentProvider\
	UNIX_ProtectedSpaceExtentProvider\
	UNIX_PhysicalExtentProvider\
	UNIX_DatabaseSegmentProvider\
	UNIX_AggregatePExtentProvider\
	UNIX_VolumeSetProvider\
	UNIX_OpaqueManagementDataProvider\
	UNIX_AggregatePSExtentProvider\
	UNIX_CacheMemoryProvider\
	UNIX_VolatileStorageProvider\
	UNIX_NonVolatileStorageProvider\
	UNIX_PrinterProvider\
	UNIX_CurrentSensorProvider\
	UNIX_TemperatureSensorProvider\
	UNIX_VoltageSensorProvider\
	UNIX_TachometerProvider\
	UNIX_MultiStateSensorProvider\
	UNIX_BinarySensorProvider\
	UNIX_DiscreteSensorProvider\
	UNIX_CableModemProvider\
	UNIX_ADSLModemProvider\
	UNIX_VDSLModemProvider\
	UNIX_HDSLModemProvider\
	UNIX_SDSLModemProvider\
	UNIX_UnimodemProvider\
	UNIX_ISDNModemProvider\
	UNIX_KeyboardProvider\
	UNIX_PointingDeviceProvider\
	UNIX_DesktopMonitorProvider\
	UNIX_FlatPanelProvider\
	UNIX_ProcessorProvider\
	UNIX_VideoHeadProvider\
	UNIX_FingerprintReaderProvider\
	UNIX_DoorProvider\
	UNIX_SmartCardProvider\
	UNIX_NetworkPortProvider\
	UNIX_WiFiPortProvider\
	UNIX_EthernetPortProvider\
	UNIX_LLDPEthernetPortProvider\
	UNIX_DataCenterEthernetPortProvider\
	UNIX_SASPortProvider\
	UNIX_IBPortProvider\
	UNIX_FCPortProvider\
	UNIX_WirelessPortProvider\
	UNIX_TokenRingPortProvider\
	UNIX_DAPortProvider\
	UNIX_SerialPortProvider\
	UNIX_ATAPortProvider\
	UNIX_USBPortProvider\
	UNIX_PCIPortProvider\
	UNIX_SPIPortProvider\
	UNIX_ParallelPortProvider\
	UNIX_FibrePortProvider\
	UNIX_WatchdogProvider\
	UNIX_EthernetAdapterProvider\
	UNIX_TokenRingAdapterProvider\
	UNIX_FibreChannelAdapterProvider\
	UNIX_IndicatorLEDProvider\
	UNIX_ElectricalSwitchProvider\
	UNIX_ProtocolControllerProvider\
	UNIX_SCSIProtocolControllerProvider\
	UNIX_WiFiRadioProvider\
	UNIX_InterLibraryPortProvider\
	UNIX_LimitedAccessPortProvider\
	UNIX_SmartCardReaderProvider\
	UNIX_PCIBridgeProvider\
	UNIX_PCIeSwitchProvider\
	UNIX_PortControllerProvider\
	UNIX_IBPortControllerProvider\
	UNIX_ParallelControllerProvider\
	UNIX_InfraredControllerProvider\
	UNIX_ManagementControllerProvider\
	UNIX_SSAControllerProvider\
	UNIX_AGPVideoControllerProvider\
	UNIX_PCVideoControllerProvider\
	UNIX_SerialControllerProvider\
	UNIX_DisplayControllerProvider\
	UNIX_AGPVideoDisplayControllerProvider\
	UNIX_USBControllerProvider\
	UNIX_IDEControllerProvider\
	UNIX_PCMCIAControllerProvider\
	UNIX_SCSIControllerProvider\
	UNIX_ESCONControllerProvider\
	UNIX_DeviceTrayProvider\
	UNIX_PassThroughModuleProvider\
	UNIX_FanProvider\
	UNIX_RefrigerationProvider\
	UNIX_HeatPipeProvider\
	UNIX_TPMProvider\
	UNIX_ScannerProvider

EXTRA_LIBRARIES = \
	-lpegprovider \
	-lpegclient \
	-lpegcommon \
	-lpegquerycommon \
	-lpegqueryexpression \
	-lpegcql \
	-lpegwql \
	-lpthread \
	-lutil \
	-lkvm

include $(ROOT)/mak/dynamic-library.mak





